//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0000.3543")]
	public enum msdyn_timeentry_msdyn_entrystatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Returned = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 192350003,
	}
}