//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "7.0.0000.3543")]
	public enum msdyn_expensecategorybehavior
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mandatory = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Optional = 192350000,
	}
}