//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum AccountState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Business that represents a customer or potential customer. The company that is billed in business transactions.
    /// </summary>
    public partial class Account : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Account() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "account";

        public const int EntityTypeCode = 1;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Select a category to indicate whether the customer account is standard or preferred.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue AccountCategoryCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("accountcategorycode");
            }
            set
            {
                this.SetAttributeValue("accountcategorycode", value);
                this.OnPropertyChanged("AccountCategoryCode");
            }
        }

        /// <summary>
        /// Select a classification code to indicate the potential value of the customer account based on the projected return on investment, cooperation level, sales cycle length or other criteria.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue AccountClassificationCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("accountclassificationcode");
            }
            set
            {
                this.SetAttributeValue("accountclassificationcode", value);
                this.OnPropertyChanged("AccountClassificationCode");
            }
        }

        /// <summary>
        /// Unique identifier of the account.
        /// </summary>
        public System.Nullable<System.Guid> AccountId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("accountid");
            }
            set
            {
                this.SetAttributeValue("accountid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("AccountId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.AccountId = value;
            }
        }

        /// <summary>
        /// Type an ID number or code for the account to quickly search and identify the account in system views.
        /// </summary>
        public string AccountNumber
        {
            get
            {
                return this.GetAttributeValue<string>("accountnumber");
            }
            set
            {
                this.SetAttributeValue("accountnumber", value);
                this.OnPropertyChanged("AccountNumber");
            }
        }

        /// <summary>
        /// Select a rating to indicate the value of the customer account.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue AccountRatingCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("accountratingcode");
            }
            set
            {
                this.SetAttributeValue("accountratingcode", value);
                this.OnPropertyChanged("AccountRatingCode");
            }
        }

        /// <summary>
        /// Unique identifier for address 1.
        /// </summary>
        public System.Nullable<System.Guid> Address1_AddressId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("address1_addressid");
            }
            set
            {
                this.SetAttributeValue("address1_addressid", value);
                this.OnPropertyChanged("Address1_AddressId");
            }
        }

        /// <summary>
        /// Select the primary address type.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address1_AddressTypeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address1_addresstypecode");
            }
            set
            {
                this.SetAttributeValue("address1_addresstypecode", value);
                this.OnPropertyChanged("Address1_AddressTypeCode");
            }
        }

        /// <summary>
        /// Type the city for the primary address.
        /// </summary>
        public string Address1_City
        {
            get
            {
                return this.GetAttributeValue<string>("address1_city");
            }
            set
            {
                this.SetAttributeValue("address1_city", value);
                this.OnPropertyChanged("Address1_City");
            }
        }

        /// <summary>
        /// Shows the complete primary address.
        /// </summary>
        public string Address1_Composite
        {
            get
            {
                return this.GetAttributeValue<string>("address1_composite");
            }
        }

        /// <summary>
        /// Type the country or region for the primary address.
        /// </summary>
        public string Address1_Country
        {
            get
            {
                return this.GetAttributeValue<string>("address1_country");
            }
            set
            {
                this.SetAttributeValue("address1_country", value);
                this.OnPropertyChanged("Address1_Country");
            }
        }

        /// <summary>
        /// Type the county for the primary address.
        /// </summary>
        public string Address1_County
        {
            get
            {
                return this.GetAttributeValue<string>("address1_county");
            }
            set
            {
                this.SetAttributeValue("address1_county", value);
                this.OnPropertyChanged("Address1_County");
            }
        }

        /// <summary>
        /// Type the fax number associated with the primary address.
        /// </summary>
        public string Address1_Fax
        {
            get
            {
                return this.GetAttributeValue<string>("address1_fax");
            }
            set
            {
                this.SetAttributeValue("address1_fax", value);
                this.OnPropertyChanged("Address1_Fax");
            }
        }

        /// <summary>
        /// Select the freight terms for the primary address to make sure shipping orders are processed correctly.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address1_FreightTermsCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address1_freighttermscode");
            }
            set
            {
                this.SetAttributeValue("address1_freighttermscode", value);
                this.OnPropertyChanged("Address1_FreightTermsCode");
            }
        }

        /// <summary>
        /// Type the latitude value for the primary address for use in mapping and other applications.
        /// </summary>
        public System.Nullable<double> Address1_Latitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("address1_latitude");
            }
            set
            {
                this.SetAttributeValue("address1_latitude", value);
                this.OnPropertyChanged("Address1_Latitude");
            }
        }

        /// <summary>
        /// Type the first line of the primary address.
        /// </summary>
        public string Address1_Line1
        {
            get
            {
                return this.GetAttributeValue<string>("address1_line1");
            }
            set
            {
                this.SetAttributeValue("address1_line1", value);
                this.OnPropertyChanged("Address1_Line1");
            }
        }

        /// <summary>
        /// Type the second line of the primary address.
        /// </summary>
        public string Address1_Line2
        {
            get
            {
                return this.GetAttributeValue<string>("address1_line2");
            }
            set
            {
                this.SetAttributeValue("address1_line2", value);
                this.OnPropertyChanged("Address1_Line2");
            }
        }

        /// <summary>
        /// Type the third line of the primary address.
        /// </summary>
        public string Address1_Line3
        {
            get
            {
                return this.GetAttributeValue<string>("address1_line3");
            }
            set
            {
                this.SetAttributeValue("address1_line3", value);
                this.OnPropertyChanged("Address1_Line3");
            }
        }

        /// <summary>
        /// Type the longitude value for the primary address for use in mapping and other applications.
        /// </summary>
        public System.Nullable<double> Address1_Longitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("address1_longitude");
            }
            set
            {
                this.SetAttributeValue("address1_longitude", value);
                this.OnPropertyChanged("Address1_Longitude");
            }
        }

        /// <summary>
        /// Type a descriptive name for the primary address, such as Corporate Headquarters.
        /// </summary>
        public string Address1_Name
        {
            get
            {
                return this.GetAttributeValue<string>("address1_name");
            }
            set
            {
                this.SetAttributeValue("address1_name", value);
                this.OnPropertyChanged("Address1_Name");
            }
        }

        /// <summary>
        /// Type the ZIP Code or postal code for the primary address.
        /// </summary>
        public string Address1_PostalCode
        {
            get
            {
                return this.GetAttributeValue<string>("address1_postalcode");
            }
            set
            {
                this.SetAttributeValue("address1_postalcode", value);
                this.OnPropertyChanged("Address1_PostalCode");
            }
        }

        /// <summary>
        /// Type the post office box number of the primary address.
        /// </summary>
        public string Address1_PostOfficeBox
        {
            get
            {
                return this.GetAttributeValue<string>("address1_postofficebox");
            }
            set
            {
                this.SetAttributeValue("address1_postofficebox", value);
                this.OnPropertyChanged("Address1_PostOfficeBox");
            }
        }

        /// <summary>
        /// Type the name of the main contact at the account's primary address.
        /// </summary>
        public string Address1_PrimaryContactName
        {
            get
            {
                return this.GetAttributeValue<string>("address1_primarycontactname");
            }
            set
            {
                this.SetAttributeValue("address1_primarycontactname", value);
                this.OnPropertyChanged("Address1_PrimaryContactName");
            }
        }

        /// <summary>
        /// Select a shipping method for deliveries sent to this address.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address1_ShippingMethodCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address1_shippingmethodcode");
            }
            set
            {
                this.SetAttributeValue("address1_shippingmethodcode", value);
                this.OnPropertyChanged("Address1_ShippingMethodCode");
            }
        }

        /// <summary>
        /// Type the state or province of the primary address.
        /// </summary>
        public string Address1_StateOrProvince
        {
            get
            {
                return this.GetAttributeValue<string>("address1_stateorprovince");
            }
            set
            {
                this.SetAttributeValue("address1_stateorprovince", value);
                this.OnPropertyChanged("Address1_StateOrProvince");
            }
        }

        /// <summary>
        /// Type the main phone number associated with the primary address.
        /// </summary>
        public string Address1_Telephone1
        {
            get
            {
                return this.GetAttributeValue<string>("address1_telephone1");
            }
            set
            {
                this.SetAttributeValue("address1_telephone1", value);
                this.OnPropertyChanged("Address1_Telephone1");
            }
        }

        /// <summary>
        /// Type a second phone number associated with the primary address.
        /// </summary>
        public string Address1_Telephone2
        {
            get
            {
                return this.GetAttributeValue<string>("address1_telephone2");
            }
            set
            {
                this.SetAttributeValue("address1_telephone2", value);
                this.OnPropertyChanged("Address1_Telephone2");
            }
        }

        /// <summary>
        /// Type a third phone number associated with the primary address.
        /// </summary>
        public string Address1_Telephone3
        {
            get
            {
                return this.GetAttributeValue<string>("address1_telephone3");
            }
            set
            {
                this.SetAttributeValue("address1_telephone3", value);
                this.OnPropertyChanged("Address1_Telephone3");
            }
        }

        /// <summary>
        /// Type the UPS zone of the primary address to make sure shipping charges are calculated correctly and deliveries are made promptly, if shipped by UPS.
        /// </summary>
        public string Address1_UPSZone
        {
            get
            {
                return this.GetAttributeValue<string>("address1_upszone");
            }
            set
            {
                this.SetAttributeValue("address1_upszone", value);
                this.OnPropertyChanged("Address1_UPSZone");
            }
        }

        /// <summary>
        /// Select the time zone, or UTC offset, for this address so that other people can reference it when they contact someone at this address.
        /// </summary>
        public System.Nullable<int> Address1_UTCOffset
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("address1_utcoffset");
            }
            set
            {
                this.SetAttributeValue("address1_utcoffset", value);
                this.OnPropertyChanged("Address1_UTCOffset");
            }
        }

        /// <summary>
        /// Unique identifier for address 2.
        /// </summary>
        public System.Nullable<System.Guid> Address2_AddressId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("address2_addressid");
            }
            set
            {
                this.SetAttributeValue("address2_addressid", value);
                this.OnPropertyChanged("Address2_AddressId");
            }
        }

        /// <summary>
        /// Select the secondary address type.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address2_AddressTypeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address2_addresstypecode");
            }
            set
            {
                this.SetAttributeValue("address2_addresstypecode", value);
                this.OnPropertyChanged("Address2_AddressTypeCode");
            }
        }

        /// <summary>
        /// Type the city for the secondary address.
        /// </summary>
        public string Address2_City
        {
            get
            {
                return this.GetAttributeValue<string>("address2_city");
            }
            set
            {
                this.SetAttributeValue("address2_city", value);
                this.OnPropertyChanged("Address2_City");
            }
        }

        /// <summary>
        /// Shows the complete secondary address.
        /// </summary>
        public string Address2_Composite
        {
            get
            {
                return this.GetAttributeValue<string>("address2_composite");
            }
        }

        /// <summary>
        /// Type the country or region for the secondary address.
        /// </summary>
        public string Address2_Country
        {
            get
            {
                return this.GetAttributeValue<string>("address2_country");
            }
            set
            {
                this.SetAttributeValue("address2_country", value);
                this.OnPropertyChanged("Address2_Country");
            }
        }

        /// <summary>
        /// Type the county for the secondary address.
        /// </summary>
        public string Address2_County
        {
            get
            {
                return this.GetAttributeValue<string>("address2_county");
            }
            set
            {
                this.SetAttributeValue("address2_county", value);
                this.OnPropertyChanged("Address2_County");
            }
        }

        /// <summary>
        /// Type the fax number associated with the secondary address.
        /// </summary>
        public string Address2_Fax
        {
            get
            {
                return this.GetAttributeValue<string>("address2_fax");
            }
            set
            {
                this.SetAttributeValue("address2_fax", value);
                this.OnPropertyChanged("Address2_Fax");
            }
        }

        /// <summary>
        /// Select the freight terms for the secondary address to make sure shipping orders are processed correctly.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address2_FreightTermsCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address2_freighttermscode");
            }
            set
            {
                this.SetAttributeValue("address2_freighttermscode", value);
                this.OnPropertyChanged("Address2_FreightTermsCode");
            }
        }

        /// <summary>
        /// Type the latitude value for the secondary address for use in mapping and other applications.
        /// </summary>
        public System.Nullable<double> Address2_Latitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("address2_latitude");
            }
            set
            {
                this.SetAttributeValue("address2_latitude", value);
                this.OnPropertyChanged("Address2_Latitude");
            }
        }

        /// <summary>
        /// Type the first line of the secondary address.
        /// </summary>
        public string Address2_Line1
        {
            get
            {
                return this.GetAttributeValue<string>("address2_line1");
            }
            set
            {
                this.SetAttributeValue("address2_line1", value);
                this.OnPropertyChanged("Address2_Line1");
            }
        }

        /// <summary>
        /// Type the second line of the secondary address.
        /// </summary>
        public string Address2_Line2
        {
            get
            {
                return this.GetAttributeValue<string>("address2_line2");
            }
            set
            {
                this.SetAttributeValue("address2_line2", value);
                this.OnPropertyChanged("Address2_Line2");
            }
        }

        /// <summary>
        /// Type the third line of the secondary address.
        /// </summary>
        public string Address2_Line3
        {
            get
            {
                return this.GetAttributeValue<string>("address2_line3");
            }
            set
            {
                this.SetAttributeValue("address2_line3", value);
                this.OnPropertyChanged("Address2_Line3");
            }
        }

        /// <summary>
        /// Type the longitude value for the secondary address for use in mapping and other applications.
        /// </summary>
        public System.Nullable<double> Address2_Longitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("address2_longitude");
            }
            set
            {
                this.SetAttributeValue("address2_longitude", value);
                this.OnPropertyChanged("Address2_Longitude");
            }
        }

        /// <summary>
        /// Type a descriptive name for the secondary address, such as Corporate Headquarters.
        /// </summary>
        public string Address2_Name
        {
            get
            {
                return this.GetAttributeValue<string>("address2_name");
            }
            set
            {
                this.SetAttributeValue("address2_name", value);
                this.OnPropertyChanged("Address2_Name");
            }
        }

        /// <summary>
        /// Type the ZIP Code or postal code for the secondary address.
        /// </summary>
        public string Address2_PostalCode
        {
            get
            {
                return this.GetAttributeValue<string>("address2_postalcode");
            }
            set
            {
                this.SetAttributeValue("address2_postalcode", value);
                this.OnPropertyChanged("Address2_PostalCode");
            }
        }

        /// <summary>
        /// Type the post office box number of the secondary address.
        /// </summary>
        public string Address2_PostOfficeBox
        {
            get
            {
                return this.GetAttributeValue<string>("address2_postofficebox");
            }
            set
            {
                this.SetAttributeValue("address2_postofficebox", value);
                this.OnPropertyChanged("Address2_PostOfficeBox");
            }
        }

        /// <summary>
        /// Type the name of the main contact at the account's secondary address.
        /// </summary>
        public string Address2_PrimaryContactName
        {
            get
            {
                return this.GetAttributeValue<string>("address2_primarycontactname");
            }
            set
            {
                this.SetAttributeValue("address2_primarycontactname", value);
                this.OnPropertyChanged("Address2_PrimaryContactName");
            }
        }

        /// <summary>
        /// Select a shipping method for deliveries sent to this address.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue Address2_ShippingMethodCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("address2_shippingmethodcode");
            }
            set
            {
                this.SetAttributeValue("address2_shippingmethodcode", value);
                this.OnPropertyChanged("Address2_ShippingMethodCode");
            }
        }

        /// <summary>
        /// Type the state or province of the secondary address.
        /// </summary>
        public string Address2_StateOrProvince
        {
            get
            {
                return this.GetAttributeValue<string>("address2_stateorprovince");
            }
            set
            {
                this.SetAttributeValue("address2_stateorprovince", value);
                this.OnPropertyChanged("Address2_StateOrProvince");
            }
        }

        /// <summary>
        /// Type the main phone number associated with the secondary address.
        /// </summary>
        public string Address2_Telephone1
        {
            get
            {
                return this.GetAttributeValue<string>("address2_telephone1");
            }
            set
            {
                this.SetAttributeValue("address2_telephone1", value);
                this.OnPropertyChanged("Address2_Telephone1");
            }
        }

        /// <summary>
        /// Type a second phone number associated with the secondary address.
        /// </summary>
        public string Address2_Telephone2
        {
            get
            {
                return this.GetAttributeValue<string>("address2_telephone2");
            }
            set
            {
                this.SetAttributeValue("address2_telephone2", value);
                this.OnPropertyChanged("Address2_Telephone2");
            }
        }

        /// <summary>
        /// Type a third phone number associated with the secondary address.
        /// </summary>
        public string Address2_Telephone3
        {
            get
            {
                return this.GetAttributeValue<string>("address2_telephone3");
            }
            set
            {
                this.SetAttributeValue("address2_telephone3", value);
                this.OnPropertyChanged("Address2_Telephone3");
            }
        }

        /// <summary>
        /// Type the UPS zone of the secondary address to make sure shipping charges are calculated correctly and deliveries are made promptly, if shipped by UPS.
        /// </summary>
        public string Address2_UPSZone
        {
            get
            {
                return this.GetAttributeValue<string>("address2_upszone");
            }
            set
            {
                this.SetAttributeValue("address2_upszone", value);
                this.OnPropertyChanged("Address2_UPSZone");
            }
        }

        /// <summary>
        /// Select the time zone, or UTC offset, for this address so that other people can reference it when they contact someone at this address.
        /// </summary>
        public System.Nullable<int> Address2_UTCOffset
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("address2_utcoffset");
            }
            set
            {
                this.SetAttributeValue("address2_utcoffset", value);
                this.OnPropertyChanged("Address2_UTCOffset");
            }
        }

        /// <summary>
        /// For system use only.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging30
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging30");
            }
        }

        /// <summary>
        /// The base currency equivalent of the aging 30 field.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging30_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging30_base");
            }
        }

        /// <summary>
        /// For system use only.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging60
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging60");
            }
        }

        /// <summary>
        /// The base currency equivalent of the aging 60 field.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging60_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging60_base");
            }
        }

        /// <summary>
        /// For system use only.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging90
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging90");
            }
        }

        /// <summary>
        /// The base currency equivalent of the aging 90 field.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Aging90_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("aging90_base");
            }
        }

        /// <summary>
        /// Select the legal designation or other business type of the account for contracts or reporting purposes.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue BusinessTypeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("businesstypecode");
            }
            set
            {
                this.SetAttributeValue("businesstypecode", value);
                this.OnPropertyChanged("BusinessTypeCode");
            }
        }

        /// <summary>
        /// Shows who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Shows the external party who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedByExternalParty
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdbyexternalparty");
            }
        }

        /// <summary>
        /// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Shows who created the record on behalf of another user.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Type the credit limit of the account. This is a useful reference when you address invoice and accounting issues with the customer.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money CreditLimit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("creditlimit");
            }
            set
            {
                this.SetAttributeValue("creditlimit", value);
                this.OnPropertyChanged("CreditLimit");
            }
        }

        /// <summary>
        /// Shows the credit limit converted to the system's default base currency for reporting purposes.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money CreditLimit_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("creditlimit_base");
            }
        }

        /// <summary>
        /// Select whether the credit for the account is on hold. This is a useful reference while addressing the invoice and accounting issues with the customer.
        /// </summary>
        public System.Nullable<bool> CreditOnHold
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("creditonhold");
            }
            set
            {
                this.SetAttributeValue("creditonhold", value);
                this.OnPropertyChanged("CreditOnHold");
            }
        }

        /// <summary>
        /// Select the size category or range of the account for segmentation and reporting purposes.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue CustomerSizeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("customersizecode");
            }
            set
            {
                this.SetAttributeValue("customersizecode", value);
                this.OnPropertyChanged("CustomerSizeCode");
            }
        }

        /// <summary>
        /// Select the category that best describes the relationship between the account and your organization.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue CustomerTypeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("customertypecode");
            }
            set
            {
                this.SetAttributeValue("customertypecode", value);
                this.OnPropertyChanged("CustomerTypeCode");
            }
        }

        /// <summary>
        /// Choose the default price list associated with the account to make sure the correct product prices for this customer are applied in sales opportunities, quotes, and orders.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference DefaultPriceLevelId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("defaultpricelevelid");
            }
            set
            {
                this.SetAttributeValue("defaultpricelevelid", value);
                this.OnPropertyChanged("DefaultPriceLevelId");
            }
        }

        /// <summary>
        /// Type additional information to describe the account, such as an excerpt from the company's website.
        /// </summary>
        public string Description
        {
            get
            {
                return this.GetAttributeValue<string>("description");
            }
            set
            {
                this.SetAttributeValue("description", value);
                this.OnPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Select whether the account allows bulk email sent through campaigns. If Do Not Allow is selected, the account can be added to marketing lists, but is excluded from email.
        /// </summary>
        public System.Nullable<bool> DoNotBulkEMail
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotbulkemail");
            }
            set
            {
                this.SetAttributeValue("donotbulkemail", value);
                this.OnPropertyChanged("DoNotBulkEMail");
            }
        }

        /// <summary>
        /// Select whether the account allows bulk postal mail sent through marketing campaigns or quick campaigns. If Do Not Allow is selected, the account can be added to marketing lists, but will be excluded from the postal mail.
        /// </summary>
        public System.Nullable<bool> DoNotBulkPostalMail
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotbulkpostalmail");
            }
            set
            {
                this.SetAttributeValue("donotbulkpostalmail", value);
                this.OnPropertyChanged("DoNotBulkPostalMail");
            }
        }

        /// <summary>
        /// Select whether the account allows direct email sent from Microsoft Dynamics 365.
        /// </summary>
        public System.Nullable<bool> DoNotEMail
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotemail");
            }
            set
            {
                this.SetAttributeValue("donotemail", value);
                this.OnPropertyChanged("DoNotEMail");
            }
        }

        /// <summary>
        /// Select whether the account allows faxes. If Do Not Allow is selected, the account will be excluded from fax activities distributed in marketing campaigns.
        /// </summary>
        public System.Nullable<bool> DoNotFax
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotfax");
            }
            set
            {
                this.SetAttributeValue("donotfax", value);
                this.OnPropertyChanged("DoNotFax");
            }
        }

        /// <summary>
        /// Select whether the account allows phone calls. If Do Not Allow is selected, the account will be excluded from phone call activities distributed in marketing campaigns.
        /// </summary>
        public System.Nullable<bool> DoNotPhone
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotphone");
            }
            set
            {
                this.SetAttributeValue("donotphone", value);
                this.OnPropertyChanged("DoNotPhone");
            }
        }

        /// <summary>
        /// Select whether the account allows direct mail. If Do Not Allow is selected, the account will be excluded from letter activities distributed in marketing campaigns.
        /// </summary>
        public System.Nullable<bool> DoNotPostalMail
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotpostalmail");
            }
            set
            {
                this.SetAttributeValue("donotpostalmail", value);
                this.OnPropertyChanged("DoNotPostalMail");
            }
        }

        /// <summary>
        /// Select whether the account accepts marketing materials, such as brochures or catalogs.
        /// </summary>
        public System.Nullable<bool> DoNotSendMM
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("donotsendmm");
            }
            set
            {
                this.SetAttributeValue("donotsendmm", value);
                this.OnPropertyChanged("DoNotSendMM");
            }
        }

        /// <summary>
        /// Type the primary email address for the account.
        /// </summary>
        public string EMailAddress1
        {
            get
            {
                return this.GetAttributeValue<string>("emailaddress1");
            }
            set
            {
                this.SetAttributeValue("emailaddress1", value);
                this.OnPropertyChanged("EMailAddress1");
            }
        }

        /// <summary>
        /// Type the secondary email address for the account.
        /// </summary>
        public string EMailAddress2
        {
            get
            {
                return this.GetAttributeValue<string>("emailaddress2");
            }
            set
            {
                this.SetAttributeValue("emailaddress2", value);
                this.OnPropertyChanged("EMailAddress2");
            }
        }

        /// <summary>
        /// Type an alternate email address for the account.
        /// </summary>
        public string EMailAddress3
        {
            get
            {
                return this.GetAttributeValue<string>("emailaddress3");
            }
            set
            {
                this.SetAttributeValue("emailaddress3", value);
                this.OnPropertyChanged("EMailAddress3");
            }
        }

        /// <summary>
        /// Shows the default image for the record.
        /// </summary>
        public byte[] EntityImage
        {
            get
            {
                return this.GetAttributeValue<byte[]>("entityimage");
            }
            set
            {
                this.SetAttributeValue("entityimage", value);
                this.OnPropertyChanged("EntityImage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<long> EntityImage_Timestamp
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string EntityImage_URL
        {
            get
            {
                return this.GetAttributeValue<string>("entityimage_url");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<System.Guid> EntityImageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
            }
        }

        /// <summary>
        /// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
        /// </summary>
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Type the fax number for the account.
        /// </summary>
        public string Fax
        {
            get
            {
                return this.GetAttributeValue<string>("fax");
            }
            set
            {
                this.SetAttributeValue("fax", value);
                this.OnPropertyChanged("Fax");
            }
        }

        /// <summary>
        /// Information about whether to allow following email activity like opens, attachment views and link clicks for emails sent to the account.
        /// </summary>
        public System.Nullable<bool> FollowEmail
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("followemail");
            }
            set
            {
                this.SetAttributeValue("followemail", value);
                this.OnPropertyChanged("FollowEmail");
            }
        }

        /// <summary>
        /// Type the URL for the account's FTP site to enable users to access data and share documents.
        /// </summary>
        public string FtpSiteURL
        {
            get
            {
                return this.GetAttributeValue<string>("ftpsiteurl");
            }
            set
            {
                this.SetAttributeValue("ftpsiteurl", value);
                this.OnPropertyChanged("FtpSiteURL");
            }
        }

        /// <summary>
        /// Unique identifier of the data import or data migration that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Select the account's primary industry for use in marketing segmentation and demographic analysis.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue IndustryCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("industrycode");
            }
            set
            {
                this.SetAttributeValue("industrycode", value);
                this.OnPropertyChanged("IndustryCode");
            }
        }

        /// <summary>
        /// Contains the date and time stamp of the last on hold time.
        /// </summary>
        public System.Nullable<System.DateTime> LastOnHoldTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
            }
            set
            {
                this.SetAttributeValue("lastonholdtime", value);
                this.OnPropertyChanged("LastOnHoldTime");
            }
        }

        /// <summary>
        /// Shows the date when the account was last included in a marketing campaign or quick campaign.
        /// </summary>
        public System.Nullable<System.DateTime> LastUsedInCampaign
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastusedincampaign");
            }
            set
            {
                this.SetAttributeValue("lastusedincampaign", value);
                this.OnPropertyChanged("LastUsedInCampaign");
            }
        }

        /// <summary>
        /// Type the market capitalization of the account to identify the company's equity, used as an indicator in financial performance analysis.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money MarketCap
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("marketcap");
            }
            set
            {
                this.SetAttributeValue("marketcap", value);
                this.OnPropertyChanged("MarketCap");
            }
        }

        /// <summary>
        /// Shows the market capitalization converted to the system's default base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money MarketCap_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("marketcap_base");
            }
        }

        /// <summary>
        /// Whether is only for marketing
        /// </summary>
        public System.Nullable<bool> MarketingOnly
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("marketingonly");
            }
            set
            {
                this.SetAttributeValue("marketingonly", value);
                this.OnPropertyChanged("MarketingOnly");
            }
        }

        /// <summary>
        /// Shows the master account that the account was merged with.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference MasterId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("masterid");
            }
        }

        /// <summary>
        /// Shows whether the account has been merged with another account.
        /// </summary>
        public System.Nullable<bool> Merged
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("merged");
            }
        }

        /// <summary>
        /// Shows who last updated the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Shows the external party who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedByExternalParty
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedbyexternalparty");
            }
        }

        /// <summary>
        /// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Shows who created the record on behalf of another user.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Reference to an other account to be used for billing (only to be used if billing account differs)
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_BillingAccount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_billingaccount");
            }
            set
            {
                this.SetAttributeValue("msdyn_billingaccount", value);
                this.OnPropertyChanged("msdyn_BillingAccount");
            }
        }

        /// <summary>
        /// External Account ID from other systems.
        /// </summary>
        public string msdyn_externalaccountid
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_externalaccountid");
            }
            set
            {
                this.SetAttributeValue("msdyn_externalaccountid", value);
                this.OnPropertyChanged("msdyn_externalaccountid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_PreferredResource
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_preferredresource");
            }
            set
            {
                this.SetAttributeValue("msdyn_preferredresource", value);
                this.OnPropertyChanged("msdyn_PreferredResource");
            }
        }

        /// <summary>
        /// Default Sales Tax Code
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_SalesTaxCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_salestaxcode");
            }
            set
            {
                this.SetAttributeValue("msdyn_salestaxcode", value);
                this.OnPropertyChanged("msdyn_SalesTaxCode");
            }
        }

        /// <summary>
        /// The Service Territory this account belongs to. This is used to optimize scheduling and routing
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ServiceTerritory
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_serviceterritory");
            }
            set
            {
                this.SetAttributeValue("msdyn_serviceterritory", value);
                this.OnPropertyChanged("msdyn_ServiceTerritory");
            }
        }

        /// <summary>
        /// Select whether the account is tax exempt.
        /// </summary>
        public System.Nullable<bool> msdyn_TaxExempt
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_taxexempt");
            }
            set
            {
                this.SetAttributeValue("msdyn_taxexempt", value);
                this.OnPropertyChanged("msdyn_TaxExempt");
            }
        }

        /// <summary>
        /// Shows the government tax exempt number.
        /// </summary>
        public string msdyn_TaxExemptNumber
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_taxexemptnumber");
            }
            set
            {
                this.SetAttributeValue("msdyn_taxexemptnumber", value);
                this.OnPropertyChanged("msdyn_TaxExemptNumber");
            }
        }

        /// <summary>
        /// Enter the travel charge to include on work orders. This value will be multiplied by the travel charge type.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_TravelCharge
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_travelcharge");
            }
            set
            {
                this.SetAttributeValue("msdyn_travelcharge", value);
                this.OnPropertyChanged("msdyn_TravelCharge");
            }
        }

        /// <summary>
        /// Value of the Travel Charge in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_travelcharge_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_travelcharge_base");
            }
        }

        /// <summary>
        /// Specify how travel is charged for this account.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_TravelChargeType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_travelchargetype");
            }
            set
            {
                this.SetAttributeValue("msdyn_travelchargetype", value);
                this.OnPropertyChanged("msdyn_TravelChargeType");
            }
        }

        /// <summary>
        /// Shows the default instructions to show on new work orders.
        /// </summary>
        public string msdyn_WorkOrderInstructions
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_workorderinstructions");
            }
            set
            {
                this.SetAttributeValue("msdyn_workorderinstructions", value);
                this.OnPropertyChanged("msdyn_WorkOrderInstructions");
            }
        }

        /// <summary>
        /// Type the company or business name.
        /// </summary>
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("name");
            }
            set
            {
                this.SetAttributeValue("name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Type the number of employees that work at the account for use in marketing segmentation and demographic analysis.
        /// </summary>
        public System.Nullable<int> NumberOfEmployees
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("numberofemployees");
            }
            set
            {
                this.SetAttributeValue("numberofemployees", value);
                this.OnPropertyChanged("NumberOfEmployees");
            }
        }

        /// <summary>
        /// Shows how long, in minutes, that the record was on hold.
        /// </summary>
        public System.Nullable<int> OnHoldTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
            }
        }

        /// <summary>
        /// Number of open opportunities against an account and its child accounts.
        /// </summary>
        public System.Nullable<int> OpenDeals
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("opendeals");
            }
        }

        /// <summary>
        /// The date time for Open Deals.
        /// </summary>
        public System.Nullable<System.DateTime> OpenDeals_Date
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("opendeals_date");
            }
        }

        /// <summary>
        /// State of Open Deals.
        /// </summary>
        public System.Nullable<int> OpenDeals_State
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("opendeals_state");
            }
        }

        /// <summary>
        /// Sum of open revenue against an account and its child accounts.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money OpenRevenue
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("openrevenue");
            }
        }

        /// <summary>
        /// Sum of open revenue against an account and its child accounts.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money OpenRevenue_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("openrevenue_base");
            }
        }

        /// <summary>
        /// The date time for Open Revenue.
        /// </summary>
        public System.Nullable<System.DateTime> OpenRevenue_Date
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("openrevenue_date");
            }
        }

        /// <summary>
        /// State of Open Revenue.
        /// </summary>
        public System.Nullable<int> OpenRevenue_State
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("openrevenue_state");
            }
        }

        /// <summary>
        /// Shows the lead that the account was created from if the account was created by converting a lead in Microsoft Dynamics 365. This is used to relate the account to data on the originating lead for use in reporting and analytics.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OriginatingLeadId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("originatingleadid");
            }
            set
            {
                this.SetAttributeValue("originatingleadid", value);
                this.OnPropertyChanged("OriginatingLeadId");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Enter the user or team who is assigned to manage the record. This field is updated every time the record is assigned to a different user.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Select the account's ownership structure, such as public or private.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue OwnershipCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("ownershipcode");
            }
            set
            {
                this.SetAttributeValue("ownershipcode", value);
                this.OnPropertyChanged("OwnershipCode");
            }
        }

        /// <summary>
        /// Shows the business unit that the record owner belongs to.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier of the team who owns the account.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier of the user who owns the account.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Choose the parent account associated with this account to show parent and child businesses in reporting and analytics.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ParentAccountId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("parentaccountid");
            }
            set
            {
                this.SetAttributeValue("parentaccountid", value);
                this.OnPropertyChanged("ParentAccountId");
            }
        }

        /// <summary>
        /// For system use only. Legacy Microsoft Dynamics CRM 3.0 workflow data.
        /// </summary>
        public System.Nullable<bool> ParticipatesInWorkflow
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("participatesinworkflow");
            }
            set
            {
                this.SetAttributeValue("participatesinworkflow", value);
                this.OnPropertyChanged("ParticipatesInWorkflow");
            }
        }

        /// <summary>
        /// Select the payment terms to indicate when the customer needs to pay the total amount.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue PaymentTermsCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("paymenttermscode");
            }
            set
            {
                this.SetAttributeValue("paymenttermscode", value);
                this.OnPropertyChanged("PaymentTermsCode");
            }
        }

        /// <summary>
        /// Select the preferred day of the week for service appointments.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue PreferredAppointmentDayCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("preferredappointmentdaycode");
            }
            set
            {
                this.SetAttributeValue("preferredappointmentdaycode", value);
                this.OnPropertyChanged("PreferredAppointmentDayCode");
            }
        }

        /// <summary>
        /// Select the preferred time of day for service appointments.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue PreferredAppointmentTimeCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("preferredappointmenttimecode");
            }
            set
            {
                this.SetAttributeValue("preferredappointmenttimecode", value);
                this.OnPropertyChanged("PreferredAppointmentTimeCode");
            }
        }

        /// <summary>
        /// Select the preferred method of contact.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue PreferredContactMethodCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("preferredcontactmethodcode");
            }
            set
            {
                this.SetAttributeValue("preferredcontactmethodcode", value);
                this.OnPropertyChanged("PreferredContactMethodCode");
            }
        }

        /// <summary>
        /// Choose the account's preferred service facility or equipment to make sure services are scheduled correctly for the customer.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference PreferredEquipmentId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("preferredequipmentid");
            }
            set
            {
                this.SetAttributeValue("preferredequipmentid", value);
                this.OnPropertyChanged("PreferredEquipmentId");
            }
        }

        /// <summary>
        /// Choose the account's preferred service for reference when you schedule service activities.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference PreferredServiceId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("preferredserviceid");
            }
            set
            {
                this.SetAttributeValue("preferredserviceid", value);
                this.OnPropertyChanged("PreferredServiceId");
            }
        }

        /// <summary>
        /// Choose the preferred service representative for reference when you schedule service activities for the account.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference PreferredSystemUserId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("preferredsystemuserid");
            }
            set
            {
                this.SetAttributeValue("preferredsystemuserid", value);
                this.OnPropertyChanged("PreferredSystemUserId");
            }
        }

        /// <summary>
        /// Choose the primary contact for the account to provide quick access to contact details.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference PrimaryContactId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("primarycontactid");
            }
            set
            {
                this.SetAttributeValue("primarycontactid", value);
                this.OnPropertyChanged("PrimaryContactId");
            }
        }

        /// <summary>
        /// Primary Satori ID for Account
        /// </summary>
        public string PrimarySatoriId
        {
            get
            {
                return this.GetAttributeValue<string>("primarysatoriid");
            }
            set
            {
                this.SetAttributeValue("primarysatoriid", value);
                this.OnPropertyChanged("PrimarySatoriId");
            }
        }

        /// <summary>
        /// Primary Twitter ID for Account
        /// </summary>
        public string PrimaryTwitterId
        {
            get
            {
                return this.GetAttributeValue<string>("primarytwitterid");
            }
            set
            {
                this.SetAttributeValue("primarytwitterid", value);
                this.OnPropertyChanged("PrimaryTwitterId");
            }
        }

        /// <summary>
        /// Shows the ID of the process.
        /// </summary>
        public System.Nullable<System.Guid> ProcessId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }
            set
            {
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("ProcessId");
            }
        }

        /// <summary>
        /// Type the annual revenue for the account, used as an indicator in financial performance analysis.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Revenue
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("revenue");
            }
            set
            {
                this.SetAttributeValue("revenue", value);
                this.OnPropertyChanged("Revenue");
            }
        }

        /// <summary>
        /// Shows the annual revenue converted to the system's default base currency. The calculations use the exchange rate specified in the Currencies area.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money Revenue_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("revenue_base");
            }
        }

        /// <summary>
        /// Type the number of shares available to the public for the account. This number is used as an indicator in financial performance analysis.
        /// </summary>
        public System.Nullable<int> SharesOutstanding
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("sharesoutstanding");
            }
            set
            {
                this.SetAttributeValue("sharesoutstanding", value);
                this.OnPropertyChanged("SharesOutstanding");
            }
        }

        /// <summary>
        /// Select a shipping method for deliveries sent to the account's address to designate the preferred carrier or other delivery option.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue ShippingMethodCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("shippingmethodcode");
            }
            set
            {
                this.SetAttributeValue("shippingmethodcode", value);
                this.OnPropertyChanged("ShippingMethodCode");
            }
        }

        /// <summary>
        /// Type the Standard Industrial Classification (SIC) code that indicates the account's primary industry of business, for use in marketing segmentation and demographic analysis.
        /// </summary>
        public string SIC
        {
            get
            {
                return this.GetAttributeValue<string>("sic");
            }
            set
            {
                this.SetAttributeValue("sic", value);
                this.OnPropertyChanged("SIC");
            }
        }

        /// <summary>
        /// Choose the service level agreement (SLA) that you want to apply to the Account record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference SLAId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("slaid");
            }
            set
            {
                this.SetAttributeValue("slaid", value);
                this.OnPropertyChanged("SLAId");
            }
        }

        /// <summary>
        /// Last SLA that was applied to this case. This field is for internal use only.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference SLAInvokedId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("slainvokedid");
            }
        }

        /// <summary>
        /// Shows the ID of the stage.
        /// </summary>
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }
            set
            {
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("StageId");
            }
        }

        /// <summary>
        /// Shows whether the account is active or inactive. Inactive accounts are read-only and can't be edited unless they are reactivated.
        /// </summary>
        public System.Nullable<Common.Model.AccountState> StateCode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.AccountState)(System.Enum.ToObject(typeof(Common.Model.AccountState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("StateCode");
            }
        }

        /// <summary>
        /// Select the account's status.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue StatusCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// Type the stock exchange at which the account is listed to track their stock and financial performance of the company.
        /// </summary>
        public string StockExchange
        {
            get
            {
                return this.GetAttributeValue<string>("stockexchange");
            }
            set
            {
                this.SetAttributeValue("stockexchange", value);
                this.OnPropertyChanged("StockExchange");
            }
        }

        /// <summary>
        /// Type the main phone number for this account.
        /// </summary>
        public string Telephone1
        {
            get
            {
                return this.GetAttributeValue<string>("telephone1");
            }
            set
            {
                this.SetAttributeValue("telephone1", value);
                this.OnPropertyChanged("Telephone1");
            }
        }

        /// <summary>
        /// Type a second phone number for this account.
        /// </summary>
        public string Telephone2
        {
            get
            {
                return this.GetAttributeValue<string>("telephone2");
            }
            set
            {
                this.SetAttributeValue("telephone2", value);
                this.OnPropertyChanged("Telephone2");
            }
        }

        /// <summary>
        /// Type a third phone number for this account.
        /// </summary>
        public string Telephone3
        {
            get
            {
                return this.GetAttributeValue<string>("telephone3");
            }
            set
            {
                this.SetAttributeValue("telephone3", value);
                this.OnPropertyChanged("Telephone3");
            }
        }

        /// <summary>
        /// Select a region or territory for the account for use in segmentation and analysis.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue TerritoryCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("territorycode");
            }
            set
            {
                this.SetAttributeValue("territorycode", value);
                this.OnPropertyChanged("TerritoryCode");
            }
        }

        /// <summary>
        /// Choose the sales region or territory for the account to make sure the account is assigned to the correct representative and for use in segmentation and analysis.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TerritoryId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("territoryid");
            }
            set
            {
                this.SetAttributeValue("territoryid", value);
                this.OnPropertyChanged("TerritoryId");
            }
        }

        /// <summary>
        /// Type the stock exchange symbol for the account to track financial performance of the company. You can click the code entered in this field to access the latest trading information from MSN Money.
        /// </summary>
        public string TickerSymbol
        {
            get
            {
                return this.GetAttributeValue<string>("tickersymbol");
            }
            set
            {
                this.SetAttributeValue("tickersymbol", value);
                this.OnPropertyChanged("TickerSymbol");
            }
        }

        /// <summary>
        /// Total time spent for emails (read and write) and meetings by me in relation to account record.
        /// </summary>
        public string TimeSpentByMeOnEmailAndMeetings
        {
            get
            {
                return this.GetAttributeValue<string>("timespentbymeonemailandmeetings");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Choose the local currency for the record to make sure budgets are reported in the correct currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TransactionCurrencyId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("TransactionCurrencyId");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public string TraversedPath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }
            set
            {
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("TraversedPath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version number of the account.
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// Type the account's website URL to get quick details about the company profile.
        /// </summary>
        public string WebSiteURL
        {
            get
            {
                return this.GetAttributeValue<string>("websiteurl");
            }
            set
            {
                this.SetAttributeValue("websiteurl", value);
                this.OnPropertyChanged("WebSiteURL");
            }
        }

        /// <summary>
        /// Type the phonetic spelling of the company name, if specified in Japanese, to make sure the name is pronounced correctly in phone calls and other communications.
        /// </summary>
        public string YomiName
        {
            get
            {
                return this.GetAttributeValue<string>("yominame");
            }
            set
            {
                this.SetAttributeValue("yominame", value);
                this.OnPropertyChanged("YomiName");
            }
        }

        /// <summary>
        /// 1:N account_master_account
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.Account> Referencedaccount_master_account
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.Account>("account_master_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.Account>("account_master_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedaccount_master_account");
            }
        }

        /// <summary>
        /// 1:N account_parent_account
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.Account> Referencedaccount_parent_account
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.Account>("account_parent_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.Account>("account_parent_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedaccount_parent_account");
            }
        }

        /// <summary>
        /// 1:N Account_Tasks
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.Task> Account_Tasks
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.Task>("Account_Tasks", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.Task>("Account_Tasks", null, value);
                this.OnPropertyChanged("Account_Tasks");
            }
        }

        /// <summary>
        /// 1:N msdyn_account_account_BillingAccount
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.Account> Referencedmsdyn_account_account_BillingAccount
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.Account>("msdyn_account_account_BillingAccount", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.Account>("msdyn_account_account_BillingAccount", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedmsdyn_account_account_BillingAccount");
            }
        }

        /// <summary>
        /// 1:N msdyn_account_msdyn_project_Customer
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_project> msdyn_account_msdyn_project_Customer
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_project>("msdyn_account_msdyn_project_Customer", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_project>("msdyn_account_msdyn_project_Customer", null, value);
                this.OnPropertyChanged("msdyn_account_msdyn_project_Customer");
            }
        }

        /// <summary>
        /// N:1 account_master_account
        /// </summary>
        public Common.Model.Account Referencingaccount_master_account
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.Account>("account_master_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing);
            }
        }

        /// <summary>
        /// N:1 account_parent_account
        /// </summary>
        public Common.Model.Account Referencingaccount_parent_account
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.Account>("account_parent_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.Account>("account_parent_account", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing, value);
                this.OnPropertyChanged("Referencingaccount_parent_account");
            }
        }

        /// <summary>
        /// N:1 lk_accountbase_createdby
        /// </summary>
        public Common.Model.SystemUser lk_accountbase_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_accountbase_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_accountbase_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_accountbase_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_accountbase_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_accountbase_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_accountbase_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_accountbase_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_accountbase_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_accountbase_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_accountbase_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_account_account_BillingAccount
        /// </summary>
        public Common.Model.Account Referencingmsdyn_account_account_BillingAccount
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.Account>("msdyn_account_account_BillingAccount", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.Account>("msdyn_account_account_BillingAccount", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing, value);
                this.OnPropertyChanged("Referencingmsdyn_account_account_BillingAccount");
            }
        }

        /// <summary>
        /// N:1 system_user_accounts
        /// </summary>
        public Common.Model.SystemUser system_user_accounts
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("system_user_accounts", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.SystemUser>("system_user_accounts", null, value);
                this.OnPropertyChanged("system_user_accounts");
            }
        }

        /// <summary>
        /// N:1 transactioncurrency_account
        /// </summary>
        public Common.Model.TransactionCurrency transactioncurrency_account
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.TransactionCurrency>("transactioncurrency_account", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.TransactionCurrency>("transactioncurrency_account", null, value);
                this.OnPropertyChanged("transactioncurrency_account");
            }
        }

        /// <summary>
        /// N:1 user_accounts
        /// </summary>
        public Common.Model.SystemUser user_accounts
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("user_accounts", null);
            }
        }
    }
}
