//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum BookableResourceBookingState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Represents the line details of a resource booking.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BookableResourceBooking : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public BookableResourceBooking() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "bookableresourcebooking";

        public const int EntityTypeCode = 1145;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the resource booking.
        /// </summary>
        public System.Nullable<System.Guid> BookableResourceBookingId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("bookableresourcebookingid");
            }
            set
            {
                this.SetAttributeValue("bookableresourcebookingid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("BookableResourceBookingId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.BookableResourceBookingId = value;
            }
        }

        /// <summary>
        /// Select the status of the booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference BookingStatus
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("bookingstatus");
            }
            set
            {
                this.SetAttributeValue("bookingstatus", value);
                this.OnPropertyChanged("BookingStatus");
            }
        }

        /// <summary>
        /// Select whether the booking is solid or liquid. Solid bookings are firm and cannot be changed whereas liquid bookings can be changed.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue BookingType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("bookingtype");
            }
            set
            {
                this.SetAttributeValue("bookingtype", value);
                this.OnPropertyChanged("BookingType");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Enter the duration of the booking.
        /// </summary>
        public System.Nullable<int> Duration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("duration");
            }
            set
            {
                this.SetAttributeValue("duration", value);
                this.OnPropertyChanged("Duration");
            }
        }

        /// <summary>
        /// Enter the end date and time of the booking.
        /// </summary>
        public System.Nullable<System.DateTime> EndTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("endtime");
            }
            set
            {
                this.SetAttributeValue("endtime", value);
                this.OnPropertyChanged("EndTime");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the bookableresourcebooking with respect to the base currency.
        /// </summary>
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Shows the reference to the booking header record that represents the summary of bookings.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference Header
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("header");
            }
            set
            {
                this.SetAttributeValue("header", value);
                this.OnPropertyChanged("Header");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Shows the time that work started.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_ActualArrivalTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualarrivaltime");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualarrivaltime", value);
                this.OnPropertyChanged("msdyn_ActualArrivalTime");
            }
        }

        /// <summary>
        /// Shows the total travel duration. If you leave this field blank the system automatically determines the travel duration by calculating the resource journal details.
        /// </summary>
        public System.Nullable<int> msdyn_ActualTravelDuration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_actualtravelduration");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualtravelduration", value);
                this.OnPropertyChanged("msdyn_ActualTravelDuration");
            }
        }

        /// <summary>
        /// Agreement Booking Date from where this Booking was generated
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_AgreementBookingDate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_agreementbookingdate");
            }
            set
            {
                this.SetAttributeValue("msdyn_agreementbookingdate", value);
                this.OnPropertyChanged("msdyn_AgreementBookingDate");
            }
        }

        /// <summary>
        /// Allow the time of this booking to be displayed on the schedule assistant as available.
        /// </summary>
        public System.Nullable<bool> msdyn_AllowOverlapping
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_allowoverlapping");
            }
            set
            {
                this.SetAttributeValue("msdyn_allowoverlapping", value);
                this.OnPropertyChanged("msdyn_AllowOverlapping");
            }
        }

        /// <summary>
        /// Shows the method used to create this booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_BookingMethod
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_bookingmethod");
            }
            set
            {
                this.SetAttributeValue("msdyn_bookingmethod", value);
                this.OnPropertyChanged("msdyn_BookingMethod");
            }
        }

        /// <summary>
        /// Unique identifier for Booking Setup Metadata associated with Bookable Resource Booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_BookingSetupMetadataId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_bookingsetupmetadataid");
            }
            set
            {
                this.SetAttributeValue("msdyn_bookingsetupmetadataid", value);
                this.OnPropertyChanged("msdyn_BookingSetupMetadataId");
            }
        }

        /// <summary>
        /// Defines whether changing any of the following fields (Start Time, End Time, Status) should cascade the changes to other bookings on this work order that have the same start and end time.
        /// </summary>
        public System.Nullable<bool> msdyn_CascadeCrewChanges
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_cascadecrewchanges");
            }
            set
            {
                this.SetAttributeValue("msdyn_cascadecrewchanges", value);
                this.OnPropertyChanged("msdyn_CascadeCrewChanges");
            }
        }

        /// <summary>
        /// Estimated Arrival Time
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_EstimatedArrivalTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_estimatedarrivaltime");
            }
            set
            {
                this.SetAttributeValue("msdyn_estimatedarrivaltime", value);
                this.OnPropertyChanged("msdyn_EstimatedArrivalTime");
            }
        }

        /// <summary>
        /// Estimated Travel Duration
        /// </summary>
        public System.Nullable<int> msdyn_EstimatedTravelDuration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_estimatedtravelduration");
            }
            set
            {
                this.SetAttributeValue("msdyn_estimatedtravelduration", value);
                this.OnPropertyChanged("msdyn_EstimatedTravelDuration");
            }
        }

        /// <summary>
        /// Relationship between the glympse task and the bookable resource booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_glympsetaskId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_glympsetaskid");
            }
            set
            {
                this.SetAttributeValue("msdyn_glympsetaskid", value);
                this.OnPropertyChanged("msdyn_glympsetaskId");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public string msdyn_InternalFlags
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_internalflags");
            }
            set
            {
                this.SetAttributeValue("msdyn_internalflags", value);
                this.OnPropertyChanged("msdyn_InternalFlags");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<double> msdyn_Latitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_latitude");
            }
            set
            {
                this.SetAttributeValue("msdyn_latitude", value);
                this.OnPropertyChanged("msdyn_Latitude");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<double> msdyn_Longitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_longitude");
            }
            set
            {
                this.SetAttributeValue("msdyn_longitude", value);
                this.OnPropertyChanged("msdyn_Longitude");
            }
        }

        /// <summary>
        /// In this field you can enter the total miles the resource drove to the job site
        /// </summary>
        public System.Nullable<double> msdyn_MilesTraveled
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_milestraveled");
            }
            set
            {
                this.SetAttributeValue("msdyn_milestraveled", value);
                this.OnPropertyChanged("msdyn_MilesTraveled");
            }
        }

        /// <summary>
        /// Prevents time stamp creation if the time stamp was already created on a mobile device.
        /// </summary>
        public System.Nullable<bool> msdyn_PreventTimestampCreation
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_preventtimestampcreation");
            }
            set
            {
                this.SetAttributeValue("msdyn_preventtimestampcreation", value);
                this.OnPropertyChanged("msdyn_PreventTimestampCreation");
            }
        }

        /// <summary>
        /// Project of booking detail record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_projectid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_projectid");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectid", value);
                this.OnPropertyChanged("msdyn_projectid");
            }
        }

        /// <summary>
        /// Project team member of booking detail record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_projectteamid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_projectteamid");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectteamid", value);
                this.OnPropertyChanged("msdyn_projectteamid");
            }
        }

        /// <summary>
        /// Resource Category
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_resourcecategoryid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourcecategoryid");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourcecategoryid", value);
                this.OnPropertyChanged("msdyn_resourcecategoryid");
            }
        }

        /// <summary>
        /// Unique identifier for Resource associated with Resource Booking
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ResourceGroup
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourcegroup");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourcegroup", value);
                this.OnPropertyChanged("msdyn_ResourceGroup");
            }
        }

        /// <summary>
        /// Resource Requirement
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ResourceRequirement
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourcerequirement");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourcerequirement", value);
                this.OnPropertyChanged("msdyn_ResourceRequirement");
            }
        }

        /// <summary>
        /// This field is used for capturing signature on MoCa (using the Pen Control)
        /// </summary>
        public string msdyn_Signature
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_signature");
            }
            set
            {
                this.SetAttributeValue("msdyn_signature", value);
                this.OnPropertyChanged("msdyn_Signature");
            }
        }

        /// <summary>
        /// Shows the automatically generated text of the time slot on the schedule board.
        /// </summary>
        public string msdyn_SlotText
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_slottext");
            }
            set
            {
                this.SetAttributeValue("msdyn_slottext", value);
                this.OnPropertyChanged("msdyn_SlotText");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_TimeGroupDetailSelected
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_timegroupdetailselected");
            }
            set
            {
                this.SetAttributeValue("msdyn_timegroupdetailselected", value);
                this.OnPropertyChanged("msdyn_TimeGroupDetailSelected");
            }
        }

        /// <summary>
        /// Shows the total billable duration. If you leave this field blank the system automatically determines the billable duration by calculating the resource journal details.
        /// </summary>
        public System.Nullable<int> msdyn_TotalBillableDuration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_totalbillableduration");
            }
            set
            {
                this.SetAttributeValue("msdyn_totalbillableduration", value);
                this.OnPropertyChanged("msdyn_TotalBillableDuration");
            }
        }

        /// <summary>
        /// Shows the total break duration. If you leave this field blank the system automatically determines the break duration by calculating the resource journal details.
        /// </summary>
        public System.Nullable<int> msdyn_TotalBreakDuration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_totalbreakduration");
            }
            set
            {
                this.SetAttributeValue("msdyn_totalbreakduration", value);
                this.OnPropertyChanged("msdyn_TotalBreakDuration");
            }
        }

        /// <summary>
        /// Shows the total cost for this booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_TotalCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_totalcost", value);
                this.OnPropertyChanged("msdyn_TotalCost");
            }
        }

        /// <summary>
        /// Value of the Total Cost in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_totalcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalcost_base");
            }
        }

        /// <summary>
        /// Shows the total duration that this booking was in progress.
        /// </summary>
        public System.Nullable<int> msdyn_TotalDurationInProgress
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_totaldurationinprogress");
            }
            set
            {
                this.SetAttributeValue("msdyn_totaldurationinprogress", value);
                this.OnPropertyChanged("msdyn_TotalDurationInProgress");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<bool> msdyn_TravelTimeRescheduling
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_traveltimerescheduling");
            }
            set
            {
                this.SetAttributeValue("msdyn_traveltimerescheduling", value);
                this.OnPropertyChanged("msdyn_TravelTimeRescheduling");
            }
        }

        /// <summary>
        /// Unique identifier for Work Order associated with Resource Booking.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_WorkOrder
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_workorder");
            }
            set
            {
                this.SetAttributeValue("msdyn_workorder", value);
                this.OnPropertyChanged("msdyn_WorkOrder");
            }
        }

        /// <summary>
        /// Type a name for the booking.
        /// </summary>
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("name");
            }
            set
            {
                this.SetAttributeValue("name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Unique identifier of the user or team who owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Shows the ID of the process.
        /// </summary>
        public System.Nullable<System.Guid> ProcessId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }
            set
            {
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("ProcessId");
            }
        }

        /// <summary>
        /// Shows the resource that is booked.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference Resource
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("resource");
            }
            set
            {
                this.SetAttributeValue("resource", value);
                this.OnPropertyChanged("Resource");
            }
        }

        /// <summary>
        /// Shows the ID of the stage.
        /// </summary>
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }
            set
            {
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("StageId");
            }
        }

        /// <summary>
        /// Enter the start date and time of the booking.
        /// </summary>
        public System.Nullable<System.DateTime> StartTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("starttime");
            }
            set
            {
                this.SetAttributeValue("starttime", value);
                this.OnPropertyChanged("StartTime");
            }
        }

        /// <summary>
        /// Status of the Bookable Resource Booking
        /// </summary>
        public System.Nullable<Common.Model.BookableResourceBookingState> StateCode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.BookableResourceBookingState)(System.Enum.ToObject(typeof(Common.Model.BookableResourceBookingState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("StateCode");
            }
        }

        /// <summary>
        /// Reason for the status of the Bookable Resource Booking
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue StatusCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the BookableResourceBooking with respect to the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TransactionCurrencyId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("TransactionCurrencyId");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public string TraversedPath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }
            set
            {
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("TraversedPath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// N:1 bookableresource_bookableresourcebooking_Resource
        /// </summary>
        public Common.Model.BookableResource bookableresource_bookableresourcebooking_Resource
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.BookableResource>("bookableresource_bookableresourcebooking_Resource", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.BookableResource>("bookableresource_bookableresourcebooking_Resource", null, value);
                this.OnPropertyChanged("bookableresource_bookableresourcebooking_Resource");
            }
        }

        /// <summary>
        /// N:1 msdyn_bookableresource_bookableresourcebooking_ResourceGroup
        /// </summary>
        public Common.Model.BookableResource msdyn_bookableresource_bookableresourcebooking_ResourceGroup
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.BookableResource>("msdyn_bookableresource_bookableresourcebooking_ResourceGroup", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.BookableResource>("msdyn_bookableresource_bookableresourcebooking_ResourceGroup", null, value);
                this.OnPropertyChanged("msdyn_bookableresource_bookableresourcebooking_ResourceGroup");
            }
        }
    }
}