//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum msdyn_expensecategoryState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Main container that holds expense category information.
    /// </summary>
    public partial class msdyn_expensecategory : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_expensecategory() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_expensecategory";

        public const int EntityTypeCode = 10063;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Shows the entity instances.
        /// </summary>
        public System.Nullable<System.Guid> msdyn_expensecategoryId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_expensecategoryid");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensecategoryid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_expensecategoryId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_expensecategoryId = value;
            }
        }

        /// <summary>
        /// Select the Transaction Category associated with Expense Category.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ExpenseCategoryuId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_expensecategoryuid");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensecategoryuid", value);
                this.OnPropertyChanged("msdyn_ExpenseCategoryuId");
            }
        }

        /// <summary>
        /// Enter the type of expense
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_ExpenseType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_expensetype");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensetype", value);
                this.OnPropertyChanged("msdyn_ExpenseType");
            }
        }

        /// <summary>
        /// Type the name of the custom entity.
        /// </summary>
        public string msdyn_name
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_name");
            }
            set
            {
                this.SetAttributeValue("msdyn_name", value);
                this.OnPropertyChanged("msdyn_name");
            }
        }

        /// <summary>
        /// Shows whether the expense entry requires a receipt.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_ReceiptRequired
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_receiptrequired");
            }
            set
            {
                this.SetAttributeValue("msdyn_receiptrequired", value);
                this.OnPropertyChanged("msdyn_ReceiptRequired");
            }
        }

        /// <summary>
        /// Unique identifier for the organization
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OrganizationId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("organizationid");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Status of the Expense Category
        /// </summary>
        public System.Nullable<Common.Model.msdyn_expensecategoryState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.msdyn_expensecategoryState)(System.Enum.ToObject(typeof(Common.Model.msdyn_expensecategoryState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Expense Category
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue statuscode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_expense> msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_expense>("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_expense>("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory", null, value);
                this.OnPropertyChanged("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory");
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensecategory_createdby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensecategory_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensecategory_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensecategory_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensecategory_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensecategory_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensecategory_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensecategory_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensecategory_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensecategory_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensecategory_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensecategory_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_transactioncategory_msdyn_expensecatego
        /// </summary>
        public Common.Model.msdyn_transactioncategory msdyn_msdyn_transactioncategory_msdyn_expensecatego
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_expensecatego", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_expensecatego", null, value);
                this.OnPropertyChanged("msdyn_msdyn_transactioncategory_msdyn_expensecatego");
            }
        }

        /// <summary>
        /// N:1 organization_msdyn_expensecategory
        /// </summary>
        public Common.Model.Organization organization_msdyn_expensecategory
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.Organization>("organization_msdyn_expensecategory", null);
            }
        }
    }
}
