//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum msdyn_projecttaskState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Tasks related to project.
    /// </summary>
    public partial class msdyn_projecttask : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_projecttask() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_projecttask";

        public const int EntityTypeCode = 10092;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the project task was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Shows the exchange rate for the currency associated with the entity with respect to the base currency.
        /// </summary>
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of user who last modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Enter the value of the actual cost consumed based on work reported to be completed on the task. 
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_Actualcost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualcost", value);
                this.OnPropertyChanged("msdyn_Actualcost");
            }
        }

        /// <summary>
        /// Value of the Actual Cost in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_actualcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualcost_base");
            }
        }

        /// <summary>
        /// Shows the actual duration of the project task in days
        /// </summary>
        public System.Nullable<int> msdyn_actualdurationminutes
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_actualdurationminutes");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualdurationminutes", value);
                this.OnPropertyChanged("msdyn_actualdurationminutes");
            }
        }

        /// <summary>
        /// Shows the hours submitted against the task.
        /// </summary>
        public System.Nullable<double> msdyn_ActualEffort
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_actualeffort");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualeffort", value);
                this.OnPropertyChanged("msdyn_ActualEffort");
            }
        }

        /// <summary>
        /// Enter the actual end time of the project task.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_actualend
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualend");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualend", value);
                this.OnPropertyChanged("msdyn_actualend");
            }
        }

        /// <summary>
        /// Actual Sales Amount
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_ActualSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualsales", value);
                this.OnPropertyChanged("msdyn_ActualSales");
            }
        }

        /// <summary>
        /// Shows the value of the actual sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_actualsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualsales_base");
            }
        }

        /// <summary>
        /// Enter the actual start time of the project task.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_actualstart
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualstart");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualstart", value);
                this.OnPropertyChanged("msdyn_actualstart");
            }
        }

        /// <summary>
        /// Shows whether the aggregation is happening upstream or downstream.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_AggregationDirection
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_aggregationdirection");
            }
            set
            {
                this.SetAttributeValue("msdyn_aggregationdirection", value);
                this.OnPropertyChanged("msdyn_AggregationDirection");
            }
        }

        /// <summary>
        /// Type the project team members that are assigned to task.
        /// </summary>
        public string msdyn_AssignedResources
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_assignedresources");
            }
            set
            {
                this.SetAttributeValue("msdyn_assignedresources", value);
                this.OnPropertyChanged("msdyn_AssignedResources");
            }
        }

        /// <summary>
        /// Select the project team member that has been assigned to a task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_AssignedTeamMembers
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_assignedteammembers");
            }
            set
            {
                this.SetAttributeValue("msdyn_assignedteammembers", value);
                this.OnPropertyChanged("msdyn_AssignedTeamMembers");
            }
        }

        /// <summary>
        /// Shows whether auto scheduling was used for this task.
        /// </summary>
        public System.Nullable<bool> msdyn_autoscheduling
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_autoscheduling");
            }
            set
            {
                this.SetAttributeValue("msdyn_autoscheduling", value);
                this.OnPropertyChanged("msdyn_autoscheduling");
            }
        }

        /// <summary>
        /// Enter the forecast of the total cost to complete the task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_CostAtCompleteEstimate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costatcompleteestimate");
            }
        }

        /// <summary>
        /// Value of the Cost estimate at complete (EAC) in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_costatcompleteestimate_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costatcompleteestimate_base");
            }
        }

        /// <summary>
        /// Enter the consumption of the total cost in percentage.
        /// </summary>
        public System.Nullable<decimal> msdyn_CostConsumptionPercentage
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_costconsumptionpercentage");
            }
        }

        /// <summary>
        /// Enter a description of the project task.
        /// </summary>
        public string msdyn_description
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_description");
            }
            set
            {
                this.SetAttributeValue("msdyn_description", value);
                this.OnPropertyChanged("msdyn_description");
            }
        }

        /// <summary>
        /// Shows the duration in days for the task.
        /// </summary>
        public System.Nullable<double> msdyn_duration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_duration");
            }
            set
            {
                this.SetAttributeValue("msdyn_duration", value);
                this.OnPropertyChanged("msdyn_duration");
            }
        }

        /// <summary>
        /// Shows the effort hours required for the task.
        /// </summary>
        public System.Nullable<double> msdyn_Effort
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_effort");
            }
            set
            {
                this.SetAttributeValue("msdyn_effort", value);
                this.OnPropertyChanged("msdyn_Effort");
            }
        }

        /// <summary>
        /// Shows the forecast of total effort to complete the task.
        /// </summary>
        public System.Nullable<double> msdyn_EffortEstimateAtComplete
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_effortestimateatcomplete");
            }
            set
            {
                this.SetAttributeValue("msdyn_effortestimateatcomplete", value);
                this.OnPropertyChanged("msdyn_EffortEstimateAtComplete");
            }
        }

        /// <summary>
        /// Shows whether the task is a line task
        /// </summary>
        public System.Nullable<bool> msdyn_IsLineTask
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_islinetask");
            }
            set
            {
                this.SetAttributeValue("msdyn_islinetask", value);
                this.OnPropertyChanged("msdyn_IsLineTask");
            }
        }

        /// <summary>
        /// Show whether this task is a milestone.
        /// </summary>
        public System.Nullable<bool> msdyn_IsMilestone
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_ismilestone");
            }
            set
            {
                this.SetAttributeValue("msdyn_ismilestone", value);
                this.OnPropertyChanged("msdyn_IsMilestone");
            }
        }

        /// <summary>
        /// The id of the project task in MS Project Client.
        /// </summary>
        public string msdyn_MSProjectClientId
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_msprojectclientid");
            }
            set
            {
                this.SetAttributeValue("msdyn_msprojectclientid", value);
                this.OnPropertyChanged("msdyn_MSProjectClientId");
            }
        }

        /// <summary>
        /// Shows the number of resources that are estimated for the task. This is not the number of resources assigned to the task.
        /// </summary>
        public System.Nullable<int> msdyn_numberofresources
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_numberofresources");
            }
            set
            {
                this.SetAttributeValue("msdyn_numberofresources", value);
                this.OnPropertyChanged("msdyn_numberofresources");
            }
        }

        /// <summary>
        /// Select the summary or parent task in the hierarchy that contains a child task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_parenttask
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_parenttask");
            }
            set
            {
                this.SetAttributeValue("msdyn_parenttask", value);
                this.OnPropertyChanged("msdyn_parenttask");
            }
        }

        /// <summary>
        /// Enter the value of the cost the service provider will incur based on the estimated work and cost rates in the pricelist.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_plannedCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_plannedcost", value);
                this.OnPropertyChanged("msdyn_plannedCost");
            }
        }

        /// <summary>
        /// Enter the value of cost estimated in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_plannedcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedcost_base");
            }
        }

        /// <summary>
        /// Planned Sales Amount
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_PlannedSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_plannedsales", value);
                this.OnPropertyChanged("msdyn_PlannedSales");
            }
        }

        /// <summary>
        /// Shows the value of the planned sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_plannedsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedsales_base");
            }
        }

        /// <summary>
        /// Enter the percentage indicating work completed.
        /// </summary>
        public System.Nullable<decimal> msdyn_Progress
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_progress");
            }
            set
            {
                this.SetAttributeValue("msdyn_progress", value);
                this.OnPropertyChanged("msdyn_Progress");
            }
        }

        /// <summary>
        /// Select the project name.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_project
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_project");
            }
            set
            {
                this.SetAttributeValue("msdyn_project", value);
                this.OnPropertyChanged("msdyn_project");
            }
        }

        /// <summary>
        /// Shows the entity instances.
        /// </summary>
        public System.Nullable<System.Guid> msdyn_projecttaskId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_projecttaskid");
            }
            set
            {
                this.SetAttributeValue("msdyn_projecttaskid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_projecttaskId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_projecttaskId = value;
            }
        }

        /// <summary>
        /// Enter the cost left over that can be consumed for future work.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_RemainingCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_remainingcost", value);
                this.OnPropertyChanged("msdyn_RemainingCost");
            }
        }

        /// <summary>
        /// Shows the value of the remaining cost in the  base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_remainingcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingcost_base");
            }
        }

        /// <summary>
        /// Shows the hours remaining to complete the task.
        /// </summary>
        public System.Nullable<double> msdyn_RemainingHours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_remaininghours");
            }
            set
            {
                this.SetAttributeValue("msdyn_remaininghours", value);
                this.OnPropertyChanged("msdyn_RemainingHours");
            }
        }

        /// <summary>
        /// Remaining Sales Amount
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_RemainingSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_remainingsales", value);
                this.OnPropertyChanged("msdyn_RemainingSales");
            }
        }

        /// <summary>
        /// Shows the value of the remaining sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_remainingsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingsales_base");
            }
        }

        /// <summary>
        /// Shows the hours assigned by generic resource.
        /// </summary>
        public System.Nullable<double> msdyn_RequestedHours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_requestedhours");
            }
            set
            {
                this.SetAttributeValue("msdyn_requestedhours", value);
                this.OnPropertyChanged("msdyn_RequestedHours");
            }
        }

        /// <summary>
        /// Select the resource role for the task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_resourcecategory
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourcecategory");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourcecategory", value);
                this.OnPropertyChanged("msdyn_resourcecategory");
            }
        }

        /// <summary>
        /// Select the organizational unit of the resource who should perform the work.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ResourceOrganizationalUnitId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourceorganizationalunitid");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourceorganizationalunitid", value);
                this.OnPropertyChanged("msdyn_ResourceOrganizationalUnitId");
            }
        }

        /// <summary>
        /// Shows the utilization units for a resource that is assigned to a project task
        /// </summary>
        public System.Nullable<decimal> msdyn_ResourceUtilization
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_resourceutilization");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourceutilization", value);
                this.OnPropertyChanged("msdyn_ResourceUtilization");
            }
        }

        /// <summary>
        /// Shows the sales consumption percentage for this task.
        /// </summary>
        public System.Nullable<decimal> msdyn_SalesConsumptionPercentage
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_salesconsumptionpercentage");
            }
        }

        /// <summary>
        /// Shows the sales estimate at the completion of this task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_SalesEstimateAtComplete
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesestimateatcomplete");
            }
        }

        /// <summary>
        /// Value of the Sales Estimate At Complete (EAC) in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_salesestimateatcomplete_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesestimateatcomplete_base");
            }
        }

        /// <summary>
        /// Shows the sales variance for this task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_SalesVariance
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesvariance");
            }
        }

        /// <summary>
        /// Shows the value of the sales variance in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_salesvariance_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesvariance_base");
            }
        }

        /// <summary>
        /// Shows the scheduled duration of the project task, specified in minutes.
        /// </summary>
        public System.Nullable<int> msdyn_scheduleddurationminutes
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_scheduleddurationminutes");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduleddurationminutes", value);
                this.OnPropertyChanged("msdyn_scheduleddurationminutes");
            }
        }

        /// <summary>
        /// Enter the scheduled end time of the project.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_scheduledend
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_scheduledend");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduledend", value);
                this.OnPropertyChanged("msdyn_scheduledend");
            }
        }

        /// <summary>
        /// Shows the scheduled hours for the task.
        /// </summary>
        public System.Nullable<double> msdyn_ScheduledHours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_scheduledhours");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduledhours", value);
                this.OnPropertyChanged("msdyn_ScheduledHours");
            }
        }

        /// <summary>
        /// Enter the scheduled start time of the project task.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_scheduledstart
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_scheduledstart");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduledstart", value);
                this.OnPropertyChanged("msdyn_scheduledstart");
            }
        }

        /// <summary>
        /// Shows the variance between the estimated work and the forecasted work based on the estimate at completion (EAC).
        /// </summary>
        public System.Nullable<double> msdyn_ScheduleVariance
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_schedulevariance");
            }
            set
            {
                this.SetAttributeValue("msdyn_schedulevariance", value);
                this.OnPropertyChanged("msdyn_ScheduleVariance");
            }
        }

        /// <summary>
        /// Internal flag to avoid the update process on the estimate lines of the project task
        /// </summary>
        public System.Nullable<bool> msdyn_skipupdateestimateline
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_skipupdateestimateline");
            }
            set
            {
                this.SetAttributeValue("msdyn_skipupdateestimateline", value);
                this.OnPropertyChanged("msdyn_skipupdateestimateline");
            }
        }

        /// <summary>
        /// Type the name of the custom entity.
        /// </summary>
        public string msdyn_subject
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_subject");
            }
            set
            {
                this.SetAttributeValue("msdyn_subject", value);
                this.OnPropertyChanged("msdyn_subject");
            }
        }

        /// <summary>
        /// Select the transaction category for the task.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_transactioncategory
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_transactioncategory");
            }
            set
            {
                this.SetAttributeValue("msdyn_transactioncategory", value);
                this.OnPropertyChanged("msdyn_transactioncategory");
            }
        }

        /// <summary>
        /// Enter the variance between the estimated cost and the forecasted cost based on the estimate at completion (EAC).
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_VarianceOfCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_varianceofcost");
            }
        }

        /// <summary>
        /// Shows the value of the cost variance in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_varianceofcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_varianceofcost_base");
            }
        }

        /// <summary>
        /// Shows the ID of the task in the work breakdown structure (WBS).
        /// </summary>
        public string msdyn_WBSID
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_wbsid");
            }
            set
            {
                this.SetAttributeValue("msdyn_wbsid", value);
                this.OnPropertyChanged("msdyn_WBSID");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Contains the id of the process associated with the entity.
        /// </summary>
        public System.Nullable<System.Guid> processid
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }
            set
            {
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("processid");
            }
        }

        /// <summary>
        /// Unique identifier of the Stage.
        /// </summary>
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }
            set
            {
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("StageId");
            }
        }

        /// <summary>
        /// Status of the Project Task
        /// </summary>
        public System.Nullable<Common.Model.msdyn_projecttaskState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.msdyn_projecttaskState)(System.Enum.ToObject(typeof(Common.Model.msdyn_projecttaskState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Project Task
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue statuscode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Shows the currency associated with the entity.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TransactionCurrencyId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("TransactionCurrencyId");
            }
        }

        /// <summary>
        /// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
        /// </summary>
        public string traversedpath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }
            set
            {
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("traversedpath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_projecttask_msdyn_projecttask_parenttask
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_projecttask> Referencedmsdyn_msdyn_projecttask_msdyn_projecttask_parenttask
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_projecttask_parenttask", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_projecttask_parenttask", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedmsdyn_msdyn_projecttask_msdyn_projecttask_parenttask");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_projecttask_msdyn_timeentry_projectTask
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_timeentry> msdyn_msdyn_projecttask_msdyn_timeentry_projectTask
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_timeentry>("msdyn_msdyn_projecttask_msdyn_timeentry_projectTask", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_timeentry>("msdyn_msdyn_projecttask_msdyn_timeentry_projectTask", null, value);
                this.OnPropertyChanged("msdyn_msdyn_projecttask_msdyn_timeentry_projectTask");
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_projecttask_createdby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_projecttask_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_projecttask_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_projecttask_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_projecttask_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_projecttask_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_projecttask_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_projecttask_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_projecttask_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_projecttask_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_projecttask_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_projecttask_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_project_msdyn_projecttask_project
        /// </summary>
        public Common.Model.msdyn_project msdyn_msdyn_project_msdyn_projecttask_project
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_projecttask_project", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_projecttask_project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_projecttask_project");
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_projecttask_msdyn_projecttask_parenttask
        /// </summary>
        public Common.Model.msdyn_projecttask Referencingmsdyn_msdyn_projecttask_msdyn_projecttask_parenttask
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_projecttask_parenttask", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_projecttask>("msdyn_msdyn_projecttask_msdyn_projecttask_parenttask", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing, value);
                this.OnPropertyChanged("Referencingmsdyn_msdyn_projecttask_msdyn_projecttask_parenttask");
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_projectteam_msdyn_projecttask_AssignedTeamMembers
        /// </summary>
        public Common.Model.msdyn_projectteam msdyn_msdyn_projectteam_msdyn_projecttask_AssignedTeamMembers
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_projectteam>("msdyn_msdyn_projectteam_msdyn_projecttask_AssignedTeamMembers", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_projectteam>("msdyn_msdyn_projectteam_msdyn_projecttask_AssignedTeamMembers", null, value);
                this.OnPropertyChanged("msdyn_msdyn_projectteam_msdyn_projecttask_AssignedTeamMembers");
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory
        /// </summary>
        public Common.Model.msdyn_transactioncategory msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_transactioncategory>("msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory", null, value);
                this.OnPropertyChanged("msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory");
            }
        }

        /// <summary>
        /// N:1 TransactionCurrency_msdyn_projecttask
        /// </summary>
        public Common.Model.TransactionCurrency TransactionCurrency_msdyn_projecttask
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_projecttask", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_projecttask", null, value);
                this.OnPropertyChanged("TransactionCurrency_msdyn_projecttask");
            }
        }

        /// <summary>
        /// N:1 user_msdyn_projecttask
        /// </summary>
        public Common.Model.SystemUser user_msdyn_projecttask
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("user_msdyn_projecttask", null);
            }
        }
    }
}
