//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum msdyn_projectState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Delivery entity in an engagement.
    /// </summary>
    public partial class msdyn_project : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_project() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_project";

        public const int EntityTypeCode = 10087;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Shows the exchange rate for the currency associated with the entity with respect to the base currency.
        /// </summary>
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Shows the actual duration of the project in minutes.
        /// </summary>
        public System.Nullable<int> msdyn_actualdurationminutes
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_actualdurationminutes");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualdurationminutes", value);
                this.OnPropertyChanged("msdyn_actualdurationminutes");
            }
        }

        /// <summary>
        /// Enter the actual end time of the project.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_actualend
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualend");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualend", value);
                this.OnPropertyChanged("msdyn_actualend");
            }
        }

        /// <summary>
        /// Shows the total actual hours of the project
        /// </summary>
        public System.Nullable<decimal> msdyn_actualhours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_actualhours");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualhours", value);
                this.OnPropertyChanged("msdyn_actualhours");
            }
        }

        /// <summary>
        /// Shows the actual sales value.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_ActualSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualsales", value);
                this.OnPropertyChanged("msdyn_ActualSales");
            }
        }

        /// <summary>
        /// Shows the value of the actual sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_actualsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_actualsales_base");
            }
        }

        /// <summary>
        /// Enter the actual start time of the project.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_actualstart
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualstart");
            }
            set
            {
                this.SetAttributeValue("msdyn_actualstart", value);
                this.OnPropertyChanged("msdyn_actualstart");
            }
        }

        /// <summary>
        /// The status of the bulk generation operations running on the project entity. If no operation is running, the value is null.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_BulkGenerationStatus
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_bulkgenerationstatus");
            }
            set
            {
                this.SetAttributeValue("msdyn_bulkgenerationstatus", value);
                this.OnPropertyChanged("msdyn_BulkGenerationStatus");
            }
        }

        /// <summary>
        /// Id of the calendar for the project.
        /// </summary>
        public string msdyn_calendarid
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_calendarid");
            }
            set
            {
                this.SetAttributeValue("msdyn_calendarid", value);
                this.OnPropertyChanged("msdyn_calendarid");
            }
        }

        /// <summary>
        /// Enter the comments that are used to describe the current project status.
        /// </summary>
        public string msdyn_comments
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_comments");
            }
            set
            {
                this.SetAttributeValue("msdyn_comments", value);
                this.OnPropertyChanged("msdyn_comments");
            }
        }

        /// <summary>
        /// Select the organizational unit sponsoring the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ContractOrganizationalUnitId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_contractorganizationalunitid");
            }
            set
            {
                this.SetAttributeValue("msdyn_contractorganizationalunitid", value);
                this.OnPropertyChanged("msdyn_ContractOrganizationalUnitId");
            }
        }

        /// <summary>
        /// Shows the actual cost divided by the estimated cost at completion.
        /// </summary>
        public System.Nullable<decimal> msdyn_CostConsumption
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_costconsumption");
            }
        }

        /// <summary>
        /// Sum of Actual Cost and Remaining cost
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_CostEstimateAtComplete
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costestimateatcomplete");
            }
        }

        /// <summary>
        /// Value of the Cost estimate at completion (EAC) in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_costestimateatcomplete_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costestimateatcomplete_base");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_CostPerformence
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_costperformence");
            }
        }

        /// <summary>
        /// Variance between the estimated cost and the forecasted cost based on the estimate at completion (EAC).
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_CostVariance
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costvariance");
            }
        }

        /// <summary>
        /// Shows the value of the cost variance in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_costvariance_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_costvariance_base");
            }
        }

        /// <summary>
        /// Enter the customer who the project is associated with.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_customer
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_customer");
            }
            set
            {
                this.SetAttributeValue("msdyn_customer", value);
                this.OnPropertyChanged("msdyn_customer");
            }
        }

        /// <summary>
        /// Enter a description of the project.
        /// </summary>
        public string msdyn_description
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_description");
            }
            set
            {
                this.SetAttributeValue("msdyn_description", value);
                this.OnPropertyChanged("msdyn_description");
            }
        }

        /// <summary>
        /// This is an internal field, mainly used during import so that we don't create a team member record for the project manager.
        /// </summary>
        public System.Nullable<bool> msdyn_disablecreateofteammemberformanager
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_disablecreateofteammemberformanager");
            }
            set
            {
                this.SetAttributeValue("msdyn_disablecreateofteammemberformanager", value);
                this.OnPropertyChanged("msdyn_disablecreateofteammemberformanager");
            }
        }

        /// <summary>
        /// Shows the total of actual hours and the remaining hours.
        /// </summary>
        public System.Nullable<double> msdyn_EffortestimateatcompleteEAC
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_effortestimateatcompleteeac");
            }
            set
            {
                this.SetAttributeValue("msdyn_effortestimateatcompleteeac", value);
                this.OnPropertyChanged("msdyn_EffortestimateatcompleteEAC");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the project with respect to the base currency.
        /// </summary>
        public System.Nullable<decimal> msdyn_exchangerate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_exchangerate");
            }
            set
            {
                this.SetAttributeValue("msdyn_exchangerate", value);
                this.OnPropertyChanged("msdyn_exchangerate");
            }
        }

        /// <summary>
        /// Specifies if the project is linked to a project in MS Project
        /// </summary>
        public System.Nullable<bool> msdyn_IsLinkedToMSProjectClient
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_islinkedtomsprojectclient");
            }
            set
            {
                this.SetAttributeValue("msdyn_islinkedtomsprojectclient", value);
                this.OnPropertyChanged("msdyn_IsLinkedToMSProjectClient");
            }
        }

        /// <summary>
        /// Shows if the project is a project template.
        /// </summary>
        public System.Nullable<bool> msdyn_istemplate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_istemplate");
            }
            set
            {
                this.SetAttributeValue("msdyn_istemplate", value);
                this.OnPropertyChanged("msdyn_istemplate");
            }
        }

        /// <summary>
        /// The URL for the linked document.
        /// </summary>
        public string msdyn_linkeddocumenturl
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_linkeddocumenturl");
            }
            set
            {
                this.SetAttributeValue("msdyn_linkeddocumenturl", value);
                this.OnPropertyChanged("msdyn_linkeddocumenturl");
            }
        }

        /// <summary>
        /// Describes the project status.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_overallprojectstatus
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_overallprojectstatus");
            }
            set
            {
                this.SetAttributeValue("msdyn_overallprojectstatus", value);
                this.OnPropertyChanged("msdyn_overallprojectstatus");
            }
        }

        /// <summary>
        /// Shows the total estimate hours of the project.
        /// </summary>
        public System.Nullable<decimal> msdyn_plannedhours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_plannedhours");
            }
            set
            {
                this.SetAttributeValue("msdyn_plannedhours", value);
                this.OnPropertyChanged("msdyn_plannedhours");
            }
        }

        /// <summary>
        /// Shows the total planned sales.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_PlannedSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_plannedsales", value);
                this.OnPropertyChanged("msdyn_PlannedSales");
            }
        }

        /// <summary>
        /// Shows the value of the planned sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_plannedsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_plannedsales_base");
            }
        }

        /// <summary>
        /// Shows the actual hours divided by effort at estimate.
        /// </summary>
        public System.Nullable<decimal> msdyn_Progress
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_progress");
            }
            set
            {
                this.SetAttributeValue("msdyn_progress", value);
                this.OnPropertyChanged("msdyn_Progress");
            }
        }

        /// <summary>
        /// Shows the entity instances.
        /// </summary>
        public System.Nullable<System.Guid> msdyn_projectId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_projectid");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_projectId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_projectId = value;
            }
        }

        /// <summary>
        /// Shows the project manager assigned to the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_projectmanager
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_projectmanager");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectmanager", value);
                this.OnPropertyChanged("msdyn_projectmanager");
            }
        }

        /// <summary>
        /// Indicates if the project resource requirements are visible to the resources assigned to the project.
        /// </summary>
        public System.Nullable<bool> msdyn_projectresourcerequirementsvisibletore
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_projectresourcerequirementsvisibletore");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectresourcerequirementsvisibletore", value);
                this.OnPropertyChanged("msdyn_projectresourcerequirementsvisibletore");
            }
        }

        /// <summary>
        /// Select the Team associated with Project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_projectteamid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_projectteamid");
            }
            set
            {
                this.SetAttributeValue("msdyn_projectteamid", value);
                this.OnPropertyChanged("msdyn_projectteamid");
            }
        }

        /// <summary>
        /// Select the project template behind the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ProjectTemplate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_projecttemplate");
            }
            set
            {
                this.SetAttributeValue("msdyn_projecttemplate", value);
                this.OnPropertyChanged("msdyn_ProjectTemplate");
            }
        }

        /// <summary>
        /// Shows the difference between the estimated cost and the actual cost.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_RemainingCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_remainingcost", value);
                this.OnPropertyChanged("msdyn_RemainingCost");
            }
        }

        /// <summary>
        /// Shows the value of the remaining cost in the  base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_remainingcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingcost_base");
            }
        }

        /// <summary>
        /// Shows the difference between the estimate at completion (EAC) and the actual hours.
        /// </summary>
        public System.Nullable<double> msdyn_RemainingHours
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_remaininghours");
            }
            set
            {
                this.SetAttributeValue("msdyn_remaininghours", value);
                this.OnPropertyChanged("msdyn_RemainingHours");
            }
        }

        /// <summary>
        /// Shows the difference between estimated sales and the actual sales.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_RemainingSales
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingsales");
            }
            set
            {
                this.SetAttributeValue("msdyn_remainingsales", value);
                this.OnPropertyChanged("msdyn_RemainingSales");
            }
        }

        /// <summary>
        /// Shows the value of the remaining sales in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_remainingsales_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_remainingsales_base");
            }
        }

        /// <summary>
        /// Shows the actual sales divided by the estimated sales.
        /// </summary>
        public System.Nullable<decimal> msdyn_SalesConsumption
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_salesconsumption");
            }
        }

        /// <summary>
        /// Shows the total of actual and remaining sales.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_SalesEstimateAtCompleteEAC
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesestimateatcompleteeac");
            }
        }

        /// <summary>
        /// Value of the Sales Estimate At Complete (EAC) in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_salesestimateatcompleteeac_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesestimateatcompleteeac_base");
            }
        }

        /// <summary>
        /// Shows the contract for this project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_salesorderid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_salesorderid");
            }
            set
            {
                this.SetAttributeValue("msdyn_salesorderid", value);
                this.OnPropertyChanged("msdyn_salesorderid");
            }
        }

        /// <summary>
        /// Shows the difference between the planned sales and the sales estimate at completion (EAC).
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_SalesVariance
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesvariance");
            }
        }

        /// <summary>
        /// Shows the value of the sales variance in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_salesvariance_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salesvariance_base");
            }
        }

        /// <summary>
        /// Shows the scheduled duration of the project, specified in minutes.
        /// </summary>
        public System.Nullable<int> msdyn_scheduleddurationminutes
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_scheduleddurationminutes");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduleddurationminutes", value);
                this.OnPropertyChanged("msdyn_scheduleddurationminutes");
            }
        }

        /// <summary>
        /// Enter the scheduled end time of the project.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_scheduledend
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_scheduledend");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduledend", value);
                this.OnPropertyChanged("msdyn_scheduledend");
            }
        }

        /// <summary>
        /// Enter the scheduled start time of the project.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_scheduledstart
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_scheduledstart");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduledstart", value);
                this.OnPropertyChanged("msdyn_scheduledstart");
            }
        }

        /// <summary>
        /// Describes the schedule performance of the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_scheduleperformance
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_scheduleperformance");
            }
            set
            {
                this.SetAttributeValue("msdyn_scheduleperformance", value);
                this.OnPropertyChanged("msdyn_scheduleperformance");
            }
        }

        /// <summary>
        /// Shows the difference between the planned effort and the estimate at completion (EAC).
        /// </summary>
        public System.Nullable<double> msdyn_ScheduleVariance
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_schedulevariance");
            }
            set
            {
                this.SetAttributeValue("msdyn_schedulevariance", value);
                this.OnPropertyChanged("msdyn_ScheduleVariance");
            }
        }

        /// <summary>
        /// Shows the stage of the project.
        /// </summary>
        public string msdyn_StageName
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_stagename");
            }
            set
            {
                this.SetAttributeValue("msdyn_stagename", value);
                this.OnPropertyChanged("msdyn_StageName");
            }
        }

        /// <summary>
        /// Shows the most recent update on a status field(comments or overall project status).
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_statusupdatedon
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_statusupdatedon");
            }
            set
            {
                this.SetAttributeValue("msdyn_statusupdatedon", value);
                this.OnPropertyChanged("msdyn_statusupdatedon");
            }
        }

        /// <summary>
        /// Type the name of the custom entity.
        /// </summary>
        public string msdyn_subject
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_subject");
            }
            set
            {
                this.SetAttributeValue("msdyn_subject", value);
                this.OnPropertyChanged("msdyn_subject");
            }
        }

        /// <summary>
        /// Shows the total number of team members assigned to this project
        /// </summary>
        public System.Nullable<int> msdyn_teamsize
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_teamsize");
            }
        }

        /// <summary>
        /// Last Updated time of rollup field Team Size.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_teamsize_Date
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_teamsize_date");
            }
        }

        /// <summary>
        /// State of rollup field Team Size.
        /// </summary>
        public System.Nullable<int> msdyn_teamsize_State
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_teamsize_state");
            }
        }

        /// <summary>
        /// Shows the aggregated cost from actuals on the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_TotalActualCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalactualcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_totalactualcost", value);
                this.OnPropertyChanged("msdyn_TotalActualCost");
            }
        }

        /// <summary>
        /// Shows the value of the total actual cost in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_totalactualcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalactualcost_base");
            }
        }

        /// <summary>
        /// Shows the aggregate of the total planned cost of all the associated tasks.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_TotalPlannedCost
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalplannedcost");
            }
            set
            {
                this.SetAttributeValue("msdyn_totalplannedcost", value);
                this.OnPropertyChanged("msdyn_TotalPlannedCost");
            }
        }

        /// <summary>
        /// Shows the value of the total planned cost in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_totalplannedcost_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalplannedcost_base");
            }
        }

        /// <summary>
        /// Shows the work breakdown structure (WBS) duration in days.
        /// </summary>
        public System.Nullable<int> msdyn_wbsduration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_wbsduration");
            }
            set
            {
                this.SetAttributeValue("msdyn_wbsduration", value);
                this.OnPropertyChanged("msdyn_wbsduration");
            }
        }

        /// <summary>
        /// Select the work hour template used to create the project calendar.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_workhourtemplate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_workhourtemplate");
            }
            set
            {
                this.SetAttributeValue("msdyn_workhourtemplate", value);
                this.OnPropertyChanged("msdyn_workhourtemplate");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Contains the id of the process associated with the entity.
        /// </summary>
        public System.Nullable<System.Guid> processid
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }
            set
            {
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("processid");
            }
        }

        /// <summary>
        /// Contains the id of the stage where the entity is located.
        /// </summary>
        public System.Nullable<System.Guid> stageid
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }
            set
            {
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("stageid");
            }
        }

        /// <summary>
        /// Status of the Project
        /// </summary>
        public System.Nullable<Common.Model.msdyn_projectState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.msdyn_projectState)(System.Enum.ToObject(typeof(Common.Model.msdyn_projectState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Project
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue statuscode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Shows the currency associated with the entity.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TransactionCurrencyId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("TransactionCurrencyId");
            }
        }

        /// <summary>
        /// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
        /// </summary>
        public string traversedpath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }
            set
            {
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("traversedpath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_project_msdyn_expense_Project
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_expense> msdyn_msdyn_project_msdyn_expense_Project
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_expense>("msdyn_msdyn_project_msdyn_expense_Project", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_expense>("msdyn_msdyn_project_msdyn_expense_Project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_expense_Project");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_project_msdyn_project_ProjectTemplate
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_project> Referencedmsdyn_msdyn_project_msdyn_project_ProjectTemplate
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_project_ProjectTemplate", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_project_ProjectTemplate", Microsoft.Xrm.Sdk.Samples.EntityRole.Referenced, value);
                this.OnPropertyChanged("Referencedmsdyn_msdyn_project_msdyn_project_ProjectTemplate");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_project_msdyn_projecttask_project
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_projecttask> msdyn_msdyn_project_msdyn_projecttask_project
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_projecttask>("msdyn_msdyn_project_msdyn_projecttask_project", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_projecttask>("msdyn_msdyn_project_msdyn_projecttask_project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_projecttask_project");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_project_msdyn_projectteam_project
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_projectteam> msdyn_msdyn_project_msdyn_projectteam_project
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_projectteam>("msdyn_msdyn_project_msdyn_projectteam_project", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_projectteam>("msdyn_msdyn_project_msdyn_projectteam_project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_projectteam_project");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_project_msdyn_timeentry_project
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_timeentry> msdyn_msdyn_project_msdyn_timeentry_project
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_timeentry>("msdyn_msdyn_project_msdyn_timeentry_project", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_timeentry>("msdyn_msdyn_project_msdyn_timeentry_project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_timeentry_project");
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_project_createdby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_project_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_project_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_project_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_project_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_project_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_project_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_project_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_project_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_project_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_project_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_project_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_account_msdyn_project_Customer
        /// </summary>
        public Common.Model.Account msdyn_account_msdyn_project_Customer
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.Account>("msdyn_account_msdyn_project_Customer", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.Account>("msdyn_account_msdyn_project_Customer", null, value);
                this.OnPropertyChanged("msdyn_account_msdyn_project_Customer");
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_project_msdyn_project_ProjectTemplate
        /// </summary>
        public Common.Model.msdyn_project Referencingmsdyn_msdyn_project_msdyn_project_ProjectTemplate
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_project_ProjectTemplate", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_project_ProjectTemplate", Microsoft.Xrm.Sdk.Samples.EntityRole.Referencing, value);
                this.OnPropertyChanged("Referencingmsdyn_msdyn_project_msdyn_project_ProjectTemplate");
            }
        }

        /// <summary>
        /// N:1 msdyn_systemuser_msdyn_project_projectmanager
        /// </summary>
        public Common.Model.SystemUser msdyn_systemuser_msdyn_project_projectmanager
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("msdyn_systemuser_msdyn_project_projectmanager", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.SystemUser>("msdyn_systemuser_msdyn_project_projectmanager", null, value);
                this.OnPropertyChanged("msdyn_systemuser_msdyn_project_projectmanager");
            }
        }

        /// <summary>
        /// N:1 TransactionCurrency_msdyn_project
        /// </summary>
        public Common.Model.TransactionCurrency TransactionCurrency_msdyn_project
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_project", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_project", null, value);
                this.OnPropertyChanged("TransactionCurrency_msdyn_project");
            }
        }

        /// <summary>
        /// N:1 user_msdyn_project
        /// </summary>
        public Common.Model.SystemUser user_msdyn_project
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("user_msdyn_project", null);
            }
        }
    }
}