//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum msdyn_expensereceiptState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Table that contains expense receipt information.
    /// </summary>
    public partial class msdyn_expensereceipt : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_expensereceipt() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_expensereceipt";

        public const int EntityTypeCode = 10064;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Type the description of the receipt.
        /// </summary>
        public string msdyn_description
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_description");
            }
            set
            {
                this.SetAttributeValue("msdyn_description", value);
                this.OnPropertyChanged("msdyn_description");
            }
        }

        /// <summary>
        /// Shows the ID of the expense entry.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ExpenseId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_expenseid");
            }
            set
            {
                this.SetAttributeValue("msdyn_expenseid", value);
                this.OnPropertyChanged("msdyn_ExpenseId");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        public System.Nullable<System.Guid> msdyn_expensereceiptId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_expensereceiptid");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensereceiptid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_expensereceiptId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_expensereceiptId = value;
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Expense Receipt
        /// </summary>
        public System.Nullable<Common.Model.msdyn_expensereceiptState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.msdyn_expensereceiptState)(System.Enum.ToObject(typeof(Common.Model.msdyn_expensereceiptState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Expense Receipt
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue statuscode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensereceipt_createdby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensereceipt_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensereceipt_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensereceipt_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensereceipt_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensereceipt_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensereceipt_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensereceipt_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensereceipt_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expensereceipt_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expensereceipt_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expensereceipt_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId
        /// </summary>
        public Common.Model.msdyn_expense msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_expense>("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_expense>("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId", null, value);
                this.OnPropertyChanged("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId");
            }
        }

        /// <summary>
        /// N:1 user_msdyn_expensereceipt
        /// </summary>
        public Common.Model.SystemUser user_msdyn_expensereceipt
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("user_msdyn_expensereceipt", null);
            }
        }
    }
}
