//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Model
{
    public enum msdyn_expenseState
    {
        Active = 0,
        Inactive = 1,
    }

    /// <summary>
    /// Main container that holds expense information.
    /// </summary>
    public partial class msdyn_expense : Microsoft.Xrm.Sdk.Samples.Entity, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_expense() : base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_expense";

        public const int EntityTypeCode = 10062;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the entity with respect to the base currency.
        /// </summary>
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Enter the total amount for expense.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_Amount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_amount");
            }
            set
            {
                this.SetAttributeValue("msdyn_amount", value);
                this.OnPropertyChanged("msdyn_Amount");
            }
        }

        /// <summary>
        /// Value of the Amount in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_amount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_amount_base");
            }
        }

        /// <summary>
        /// Shows the bookable resource..
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_bookableresource
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_bookableresource");
            }
            set
            {
                this.SetAttributeValue("msdyn_bookableresource", value);
                this.OnPropertyChanged("msdyn_bookableresource");
            }
        }

        /// <summary>
        /// Enter the expense category.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ExpenseCategory
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_expensecategory");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensecategory", value);
                this.OnPropertyChanged("msdyn_ExpenseCategory");
            }
        }

        /// <summary>
        /// Shows the entity instances.
        /// </summary>
        public System.Nullable<System.Guid> msdyn_expenseId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_expenseid");
            }
            set
            {
                this.SetAttributeValue("msdyn_expenseid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_expenseId");
            }
        }

        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_expenseId = value;
            }
        }

        /// <summary>
        /// Shows the status of the expense entry.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_ExpenseStatus
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_expensestatus");
            }
            set
            {
                this.SetAttributeValue("msdyn_expensestatus", value);
                this.OnPropertyChanged("msdyn_ExpenseStatus");
            }
        }

        /// <summary>
        /// The external comments of the expense entry.
        /// </summary>
        public string msdyn_externaldescription
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_externaldescription");
            }
            set
            {
                this.SetAttributeValue("msdyn_externaldescription", value);
                this.OnPropertyChanged("msdyn_externaldescription");
            }
        }

        /// <summary>
        /// Select the manager of the expense user. This field is used for approval.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_manager
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_manager");
            }
            set
            {
                this.SetAttributeValue("msdyn_manager", value);
                this.OnPropertyChanged("msdyn_manager");
            }
        }

        /// <summary>
        /// Enter the expense's purpose.
        /// </summary>
        public string msdyn_name
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_name");
            }
            set
            {
                this.SetAttributeValue("msdyn_name", value);
                this.OnPropertyChanged("msdyn_name");
            }
        }

        /// <summary>
        /// Enter the project.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_Project
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_project");
            }
            set
            {
                this.SetAttributeValue("msdyn_project", value);
                this.OnPropertyChanged("msdyn_Project");
            }
        }

        /// <summary>
        /// Select the organizational unit at the time the entry was registered of the resource who had the expense.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference msdyn_ResourceOrganizationalUnitId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("msdyn_resourceorganizationalunitid");
            }
            set
            {
                this.SetAttributeValue("msdyn_resourceorganizationalunitid", value);
                this.OnPropertyChanged("msdyn_ResourceOrganizationalUnitId");
            }
        }

        /// <summary>
        /// Enter the sales tax amount.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_Salestaxamount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salestaxamount");
            }
            set
            {
                this.SetAttributeValue("msdyn_salestaxamount", value);
                this.OnPropertyChanged("msdyn_Salestaxamount");
            }
        }

        /// <summary>
        /// Value of the Sales tax amount in base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_salestaxamount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_salestaxamount_base");
            }
        }

        /// <summary>
        /// Shows the status that the record will be transitioned to asynchronously. Currently, this is only implemented from submission to approved.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue msdyn_targetExpenseStatus
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("msdyn_targetexpensestatus");
            }
            set
            {
                this.SetAttributeValue("msdyn_targetexpensestatus", value);
                this.OnPropertyChanged("msdyn_targetExpenseStatus");
            }
        }

        /// <summary>
        /// Shows the total amount of the expense entry.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_totalamount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalamount");
            }
        }

        /// <summary>
        /// Enter the value of the total amount in the base currency.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.Money msdyn_totalamount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.Money>("msdyn_totalamount_base");
            }
        }

        /// <summary>
        /// Enter the date of the expense transaction.
        /// </summary>
        public System.Nullable<System.DateTime> msdyn_TransactionDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_transactiondate");
            }
            set
            {
                this.SetAttributeValue("msdyn_transactiondate", value);
                this.OnPropertyChanged("msdyn_TransactionDate");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Contains the id of the process associated with the entity.
        /// </summary>
        public System.Nullable<System.Guid> processid
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }
            set
            {
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("processid");
            }
        }

        /// <summary>
        /// Contains the id of the stage where the entity is located.
        /// </summary>
        public System.Nullable<System.Guid> stageid
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }
            set
            {
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("stageid");
            }
        }

        /// <summary>
        /// Status of the Expense
        /// </summary>
        public System.Nullable<Common.Model.msdyn_expenseState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.Samples.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Common.Model.msdyn_expenseState)(System.Enum.ToObject(typeof(Common.Model.msdyn_expenseState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.Samples.OptionSetValue(((int)(value))));
                }
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Expense
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.OptionSetValue statuscode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.OptionSetValue>("statuscode");
            }
            set
            {
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Shows the currency associated with the entity.
        /// </summary>
        public Microsoft.Xrm.Sdk.Samples.EntityReference TransactionCurrencyId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Samples.EntityReference>("transactioncurrencyid");
            }
            set
            {
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("TransactionCurrencyId");
            }
        }

        /// <summary>
        /// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
        /// </summary>
        public string traversedpath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }
            set
            {
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("traversedpath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId
        /// </summary>
        public System.Collections.Generic.IEnumerable<Common.Model.msdyn_expensereceipt> msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId
        {
            get
            {
                return this.GetRelatedEntities<Common.Model.msdyn_expensereceipt>("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId", null);
            }
            set
            {
                this.SetRelatedEntities<Common.Model.msdyn_expensereceipt>("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId", null, value);
                this.OnPropertyChanged("msdyn_msdyn_expense_msdyn_expensereceipt_ExpenseId");
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expense_createdby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expense_createdby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expense_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expense_createdonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expense_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expense_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expense_modifiedby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expense_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expense_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_msdyn_expense_modifiedonbehalfby
        /// </summary>
        public Common.Model.SystemUser lk_msdyn_expense_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("lk_msdyn_expense_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory
        /// </summary>
        public Common.Model.msdyn_expensecategory msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_expensecategory>("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_expensecategory>("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory", null, value);
                this.OnPropertyChanged("msdyn_msdyn_expensecategory_msdyn_expense_ExpenseCategory");
            }
        }

        /// <summary>
        /// N:1 msdyn_msdyn_project_msdyn_expense_Project
        /// </summary>
        public Common.Model.msdyn_project msdyn_msdyn_project_msdyn_expense_Project
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_expense_Project", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.msdyn_project>("msdyn_msdyn_project_msdyn_expense_Project", null, value);
                this.OnPropertyChanged("msdyn_msdyn_project_msdyn_expense_Project");
            }
        }

        /// <summary>
        /// N:1 msdyn_systemuser_msdyn_expense_manager
        /// </summary>
        public Common.Model.SystemUser msdyn_systemuser_msdyn_expense_manager
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("msdyn_systemuser_msdyn_expense_manager", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.SystemUser>("msdyn_systemuser_msdyn_expense_manager", null, value);
                this.OnPropertyChanged("msdyn_systemuser_msdyn_expense_manager");
            }
        }

        /// <summary>
        /// N:1 TransactionCurrency_msdyn_expense
        /// </summary>
        public Common.Model.TransactionCurrency TransactionCurrency_msdyn_expense
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_expense", null);
            }
            set
            {
                this.SetRelatedEntity<Common.Model.TransactionCurrency>("TransactionCurrency_msdyn_expense", null, value);
                this.OnPropertyChanged("TransactionCurrency_msdyn_expense");
            }
        }

        /// <summary>
        /// N:1 user_msdyn_expense
        /// </summary>
        public Common.Model.SystemUser user_msdyn_expense
        {
            get
            {
                return this.GetRelatedEntity<Common.Model.SystemUser>("user_msdyn_expense", null);
            }
        }
    }
}
