//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utilities.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utilities.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Proficiency.
        /// </summary>
        public static string AddProficiency {
            get {
                return ResourceManager.GetString("AddProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        public static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting your work recommendations. Please try again later..
        /// </summary>
        public static string AnErrorOccurredWhileGettingYourWork {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileGettingYourWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application sent.
        /// </summary>
        public static string ApplicationSent {
            get {
                return ResourceManager.GetString("ApplicationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been submitted successfully.\n\nProject: {0}\nPosition: {1}.
        /// </summary>
        public static string ApplicationSentMessage {
            get {
                return ResourceManager.GetString("ApplicationSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying for this job....
        /// </summary>
        public static string ApplyingForJob {
            get {
                return ResourceManager.GetString("ApplyingForJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by compatibility.
        /// </summary>
        public static string ByCompatibilityLowercase {
            get {
                return ResourceManager.GetString("ByCompatibilityLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by duration.
        /// </summary>
        public static string ByDurationLowercase {
            get {
                return ResourceManager.GetString("ByDurationLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by earliest start.
        /// </summary>
        public static string ByEarliestStartLowercase {
            get {
                return ResourceManager.GetString("ByEarliestStartLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by my connections.
        /// </summary>
        public static string ByMyConnectionsLowercase {
            get {
                return ResourceManager.GetString("ByMyConnectionsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by skills.
        /// </summary>
        public static string BySkillsLowercase {
            get {
                return ResourceManager.GetString("BySkillsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelLowercase {
            get {
                return ResourceManager.GetString("CancelLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Receipt.
        /// </summary>
        public static string CaptureReceipt {
            get {
                return ResourceManager.GetString("CaptureReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save an expense without a category. Select a category and try saving again..
        /// </summary>
        public static string CategoryError {
            get {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change the expense category, the following information will be lost: {0}. 
        ///Do you want to continue?.
        /// </summary>
        public static string ChangeExpenseTypeWarning {
            get {
                return ResourceManager.GetString("ChangeExpenseTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}: {2}.
        /// </summary>
        public static string CollaboratorFullName {
            get {
                return ResourceManager.GetString("CollaboratorFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        public static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting your company....
        /// </summary>
        public static string ContactingYourCompanyDotDotDot {
            get {
                return ResourceManager.GetString("ContactingYourCompanyDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to org.crm.dynamics.com.
        /// </summary>
        public static string CRMServerURLPlaceHolder {
            get {
                return ResourceManager.GetString("CRMServerURLPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified date isn&apos;t valid..
        /// </summary>
        public static string DateInvalidWarning {
            get {
                return ResourceManager.GetString("DateInvalidWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DayLowercase {
            get {
                return ResourceManager.GetString("DayLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DaysLowercase {
            get {
                return ResourceManager.GetString("DaysLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myDirectory.
        /// </summary>
        public static string DefaultDirectory {
            get {
                return ResourceManager.GetString("DefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myFile.
        /// </summary>
        public static string DefaultFilename {
            get {
                return ResourceManager.GetString("DefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected items will be deleted..
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected expense will be deleted..
        /// </summary>
        public static string DeleteWarningExpense {
            get {
                return ResourceManager.GetString("DeleteWarningExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected time entry will be deleted..
        /// </summary>
        public static string DeleteWarningTime {
            get {
                return ResourceManager.GetString("DeleteWarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string DescriptionUppercase {
            get {
                return ResourceManager.GetString("DescriptionUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (HH:mm).
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        public static string DurationContainer {
            get {
                return ResourceManager.GetString("DurationContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h {1}m.
        /// </summary>
        public static string DurationHoursMinute {
            get {
                return ResourceManager.GetString("DurationHoursMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 day.
        /// </summary>
        public static string DurationLessThanOneDay {
            get {
                return ResourceManager.GetString("DurationLessThanOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationText {
            get {
                return ResourceManager.GetString("DurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest Start.
        /// </summary>
        public static string EarliestStart {
            get {
                return ResourceManager.GetString("EarliestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Online Address.
        /// </summary>
        public static string endPoint {
            get {
                return ResourceManager.GetString("endPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the authentication. To use the app, sign in to your CRM server..
        /// </summary>
        public static string errorAuthenticationCancelled {
            get {
                return ResourceManager.GetString("errorAuthenticationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to authenticate you with the server. Please try again later..
        /// </summary>
        public static string errorAuthenticationFailed {
            get {
                return ResourceManager.GetString("errorAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Project Service solution might not be set up correctly. Contact your administrator..
        /// </summary>
        public static string errorCrmRequestNotSupported {
            get {
                return ResourceManager.GetString("errorCrmRequestNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren’t connected to the Internet. Check your connection and try again..
        /// </summary>
        public static string errorNoInternet {
            get {
                return ResourceManager.GetString("errorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can’t connect to the specified server. Check the CRM server URL or your Internet connection and try again..
        /// </summary>
        public static string errorOAuthUrlRetrieveFailed {
            get {
                return ResourceManager.GetString("errorOAuthUrlRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file couldn&apos;t be opened: {0}.
        /// </summary>
        public static string ErrorOpeningFile {
            get {
                return ResourceManager.GetString("ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on the server while processing this operation..
        /// </summary>
        public static string errorRestCall {
            get {
                return ResourceManager.GetString("errorRestCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to access the application. Contact your administrator..
        /// </summary>
        public static string errorRetrievePrivilegeForUser {
            get {
                return ResourceManager.GetString("errorRetrievePrivilegeForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have access to the service. Please try signing in again..
        /// </summary>
        public static string errorServiceAccessDenied {
            get {
                return ResourceManager.GetString("errorServiceAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while contacting the service. Please contact your administrator. Error details:\n\n{0}.
        /// </summary>
        public static string errorServiceContactAdmin {
            get {
                return ResourceManager.GetString("errorServiceContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while contacting the service. Please try again later..
        /// </summary>
        public static string errorServiceUnknown {
            get {
                return ResourceManager.GetString("errorServiceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired and you have been signed out. Sign in again..
        /// </summary>
        public static string errorSessionExpired {
            get {
                return ResourceManager.GetString("errorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This expense type can&apos;t be submitted without a receipt. Attach a receipt and try submitting the expense again..
        /// </summary>
        public static string ExpenseReceiptSubmitError {
            get {
                return ResourceManager.GetString("ExpenseReceiptSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string expenseSaved {
            get {
                return ResourceManager.GetString("expenseSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Comments.
        /// </summary>
        public static string ExternalComments {
            get {
                return ResourceManager.GetString("ExternalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1} {2}.
        /// </summary>
        public static string FullDuration {
            get {
                return ResourceManager.GetString("FullDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your information....
        /// </summary>
        public static string GettingYourInfoDotDotDot {
            get {
                return ResourceManager.GetString("GettingYourInfoDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the skills on your profile. You can update your skills or add a new skill..
        /// </summary>
        public static string HereAreSkillsOnYourProfile {
            get {
                return ResourceManager.GetString("HereAreSkillsOnYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s work that fits your experience and preferences..
        /// </summary>
        public static string HeresWorkThatFits {
            get {
                return ResourceManager.GetString("HeresWorkThatFits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s work that fits your skills..
        /// </summary>
        public static string HeresWorkThatFitsBySkill {
            get {
                return ResourceManager.GetString("HeresWorkThatFitsBySkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        public static string inProcess {
            get {
                return ResourceManager.GetString("inProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Comments.
        /// </summary>
        public static string InternalComments {
            get {
                return ResourceManager.GetString("InternalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only enter positive numbers for a time entry duration. Try again with a positive number in the format HH:mm..
        /// </summary>
        public static string InvalidDuration {
            get {
                return ResourceManager.GetString("InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your connections.
        /// </summary>
        public static string InYourConnections {
            get {
                return ResourceManager.GetString("InYourConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems your profile is out of date. Would you like to update it?.
        /// </summary>
        public static string ItSeemsProfileOutOfDateWouldYouUpdate {
            get {
                return ResourceManager.GetString("ItSeemsProfileOutOfDateWouldYouUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems your profile is out of date. Here is what we have for you:.
        /// </summary>
        public static string ItSeemsYourProfileIsOutOfDate {
            get {
                return ResourceManager.GetString("ItSeemsYourProfileIsOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nJustification: {0}.
        /// </summary>
        public static string Justification {
            get {
                return ResourceManager.GetString("Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        public static string LocationUppercase {
            get {
                return ResourceManager.GetString("LocationUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in. Please wait....
        /// </summary>
        public static string LoggingInPleaseWait {
            get {
                return ResourceManager.GetString("LoggingInPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session was closed successfully..
        /// </summary>
        public static string LogOutOk {
            get {
                return ResourceManager.GetString("LogOutOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string messageTitle {
            get {
                return ResourceManager.GetString("messageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthLowercase {
            get {
                return ResourceManager.GetString("MonthLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MonthsLowercase {
            get {
                return ResourceManager.GetString("MonthsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        public static string moreDotDotDot {
            get {
                return ResourceManager.GetString("moreDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more ....
        /// </summary>
        public static string MoreReasonsText {
            get {
                return ResourceManager.GetString("MoreReasonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Connections.
        /// </summary>
        public static string MyConnections {
            get {
                return ResourceManager.GetString("MyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Expenses.
        /// </summary>
        public static string MyExpenses {
            get {
                return ResourceManager.GetString("MyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SKILLS.
        /// </summary>
        public static string MySkills {
            get {
                return ResourceManager.GetString("MySkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Time.
        /// </summary>
        public static string MyTime {
            get {
                return ResourceManager.GetString("MyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SKILLS.
        /// </summary>
        public static string NewSkills {
            get {
                return ResourceManager.GetString("NewSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries were found..
        /// </summary>
        public static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re having trouble connecting to the server. Please try again later..
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requirements.
        /// </summary>
        public static string NoRequirements {
            get {
                return ResourceManager.GetString("NoRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found..
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        public static string notApplicable {
            get {
                return ResourceManager.GetString("notApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team members.
        /// </summary>
        public static string NoTeamMembers {
            get {
                return ResourceManager.GetString("NoTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there&apos;s no work available. Please check again later..
        /// </summary>
        public static string NoWorkCurrently {
            get {
                return ResourceManager.GetString("NoWorkCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW.
        /// </summary>
        public static string OverviewUppercase {
            get {
                return ResourceManager.GetString("OverviewUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone app version is earlier than the server version. Please update this phone app..
        /// </summary>
        public static string PhoneUpdateNeeded {
            get {
                return ResourceManager.GetString("PhoneUpdateNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Microsoft Dynamics CRM Server URL..
        /// </summary>
        public static string PleaseEnterYourCRMURL {
            get {
                return ResourceManager.GetString("PleaseEnterYourCRMURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your Microsoft Dynamics CRM Server to continue..
        /// </summary>
        public static string PleaseLogInToYourCRMServer {
            get {
                return ResourceManager.GetString("PleaseLogInToYourCRMServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a proficiency.
        /// </summary>
        public static string PleaseSelectProficiency {
            get {
                return ResourceManager.GetString("PleaseSelectProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a skill..
        /// </summary>
        public static string PleaseSelectSkill {
            get {
                return ResourceManager.GetString("PleaseSelectSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we search for available jobs....
        /// </summary>
        public static string PleaseWaitWhileWeSearchDotDotDot {
            get {
                return ResourceManager.GetString("PleaseWaitWhileWeSearchDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string ProcessingDotDotDot {
            get {
                return ResourceManager.GetString("ProcessingDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency.
        /// </summary>
        public static string Proficiency {
            get {
                return ResourceManager.GetString("Proficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency determined by the system..
        /// </summary>
        public static string proficiencyBySystem {
            get {
                return ResourceManager.GetString("proficiencyBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency determined by the user. The system thinks the proficiency should be.
        /// </summary>
        public static string proficiencyByUser {
            get {
                return ResourceManager.GetString("proficiencyByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string ProficiencyNoteText {
            get {
                return ResourceManager.GetString("ProficiencyNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}{2}.
        /// </summary>
        public static string ProficiencyNoteTextJustification {
            get {
                return ResourceManager.GetString("ProficiencyNoteTextJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string ProfileColon {
            get {
                return ResourceManager.GetString("ProfileColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileLowercase {
            get {
                return ResourceManager.GetString("ProfileLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Update.
        /// </summary>
        public static string ProfileUpdate {
            get {
                return ResourceManager.GetString("ProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task.
        /// </summary>
        public static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string ReallySignOut {
            get {
                return ResourceManager.GetString("ReallySignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item can’t be recalled. Please check the data or try again later..
        /// </summary>
        public static string RecallError {
            get {
                return ResourceManager.GetString("RecallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myReceipt_{0}.jpg.
        /// </summary>
        public static string ReceiptFileName {
            get {
                return ResourceManager.GetString("ReceiptFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseReceipts.
        /// </summary>
        public static string ReceiptsDirName {
            get {
                return ResourceManager.GetString("ReceiptsDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshLowercase {
            get {
                return ResourceManager.GetString("RefreshLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIREMENTS.
        /// </summary>
        public static string RequirementsUppercase {
            get {
                return ResourceManager.GetString("RequirementsUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}|{1}.
        /// </summary>
        public static string RoleAndProject {
            get {
                return ResourceManager.GetString("RoleAndProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        public static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item can’t be saved. Please check the data or try again later..
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Project Finder Mobile.
        /// </summary>
        public static string SearchInFindWork {
            get {
                return ResourceManager.GetString("SearchInFindWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchingDotDotDot {
            get {
                return ResourceManager.GetString("SearchingDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchLowercase {
            get {
                return ResourceManager.GetString("SearchLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string SearchUppercase {
            get {
                return ResourceManager.GetString("SearchUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Proficiency.
        /// </summary>
        public static string SelectProficiency {
            get {
                return ResourceManager.GetString("SelectProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a skill.
        /// </summary>
        public static string SelectSkill {
            get {
                return ResourceManager.GetString("SelectSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the proficiency for the skills you want updated..
        /// </summary>
        public static string SetProficiencyForSkillsToUpdate {
            get {
                return ResourceManager.GetString("SetProficiencyForSkillsToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Enter the Dynamics CRM server URL, and then click Sign In.
        ///2. Enter your credentials on the next screen to complete the sign-in process..
        /// </summary>
        public static string settingsDescription {
            get {
                return ResourceManager.GetString("settingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all projects.
        /// </summary>
        public static string ShowAllProjects {
            get {
                return ResourceManager.GetString("ShowAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my projects.
        /// </summary>
        public static string ShowMyProjects {
            get {
                return ResourceManager.GetString("ShowMyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string signoutLowercase {
            get {
                return ResourceManager.GetString("signoutLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your skill selection couldn&apos;t be submitted. Please try again later..
        /// </summary>
        public static string SorrySkillSelectionNotSubmitted {
            get {
                return ResourceManager.GetString("SorrySkillSelectionNotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string sortLowercase {
            get {
                return ResourceManager.GetString("sortLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item can’t be submitted. Please check the data or try again later..
        /// </summary>
        public static string SubmitError {
            get {
                return ResourceManager.GetString("SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string SubmitLowercase {
            get {
                return ResourceManager.GetString("SubmitLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Profile Updates.
        /// </summary>
        public static string SuggestProfileUpdates {
            get {
                return ResourceManager.GetString("SuggestProfileUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM.
        /// </summary>
        public static string TeamUppercase {
            get {
                return ResourceManager.GetString("TeamUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is limited to {0} characters..
        /// </summary>
        public static string TextSizeLimitedTo {
            get {
                return ResourceManager.GetString("TextSizeLimitedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no skills on your profile. To add a skill, click Add Skill..
        /// </summary>
        public static string ThereAreNoSkillsOnYourProfile {
            get {
                return ResourceManager.GetString("ThereAreNoSkillsOnYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Entries.
        /// </summary>
        public static string TimeEntries {
            get {
                return ResourceManager.GetString("TimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entries for this date can’t exceed 24 hours..
        /// </summary>
        public static string TimeExceeded {
            get {
                return ResourceManager.GetString("TimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your unsaved data will be lost. Are you sure you want to discard all your changes?.
        /// </summary>
        public static string UnsavedDataWarning {
            get {
                return ResourceManager.GetString("UnsavedDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED SKILLS.
        /// </summary>
        public static string UpdatedSkills {
            get {
                return ResourceManager.GetString("UpdatedSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string UpdateLowercase {
            get {
                return ResourceManager.GetString("UpdateLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string UserFirstNameLastName {
            get {
                return ResourceManager.GetString("UserFirstNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        public static string WelcomeComma {
            get {
                return ResourceManager.GetString("WelcomeComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string YearLowercase {
            get {
                return ResourceManager.GetString("YearLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string YearsLowercase {
            get {
                return ResourceManager.GetString("YearsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t updated any skills..
        /// </summary>
        public static string YouHaveNotUpdated {
            get {
                return ResourceManager.GetString("YouHaveNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been submitted successfully.
        ///
        ///Project:.
        /// </summary>
        public static string YourApplicationSent {
            get {
                return ResourceManager.GetString("YourApplicationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your organization doesn&apos;t have any skills or proficiencies defined. Please contact your system administrator..
        /// </summary>
        public static string YourOrganizationHasNoSkillsDefined {
            get {
                return ResourceManager.GetString("YourOrganizationHasNoSkillsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is up to date..
        /// </summary>
        public static string YourProfileIsUpToDate {
            get {
                return ResourceManager.GetString("YourProfileIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skill selection has been submitted for updating..
        /// </summary>
        public static string YourSkillSelectionSubmitted {
            get {
                return ResourceManager.GetString("YourSkillSelectionSubmitted", resourceCulture);
            }
        }
    }
}
